function J_toe = J_toe(in1)
%J_TOE
%    J_TOE = J_TOE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    26-Jul-2020 19:30:11

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t13 = atan(5.18251222829003e-1);
t14 = atan(1.929566117647059);
t16 = 1.903089174117337e+18;
t3 = cos(t2);
t4 = sin(t2);
t5 = q_t3+q_t4+t2;
t22 = -t14;
t6 = cos(t5);
t7 = q_t5+t5;
t8 = sin(t5);
t11 = t3.*4.453122e-1;
t12 = t4.*4.453122e-1;
t9 = sin(t7);
t10 = cos(t7);
t15 = -t12;
t17 = t6.*4.453122e-1;
t18 = t8.*4.453122e-1;
t24 = q_t6+t7+t13;
t26 = q_t6+t7+t22;
t19 = t10.*4.60062e-1;
t20 = t9.*4.60062e-1;
t21 = -t18;
t25 = cos(t24);
t27 = cos(t26);
t23 = -t20;
t28 = (t16.*t25)./1.125899906842624e+19;
t29 = (t16.*t27)./1.125899906842624e+19;
t30 = -t29;
t31 = t17+t19+t28;
t32 = t21+t23+t30;
J_toe = reshape([t15+t32-sin(q_t1).*4.60062e-1,t11+t31+cos(q_t1).*4.60062e-1,0.0,t15+t32,t11+t31,0.0,t32,t31,0.0,t32,t31,0.0,t23+t30,t19+t28,0.0,t30,t28,0.0],[3,6]);
