function dG_dx = dG_dx(q1,q2,q3,q4,q5,q6)
%DG_DX
%    DG_DX = DG_DX(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Jun-2020 17:36:27

t2 = q1+q2;
t3 = q3+t2;
t4 = sin(t2);
t5 = q4+t3;
t6 = sin(t3);
t12 = t4.*2.522989668522888e+2;
t7 = q5+t5;
t8 = sin(t5);
t13 = -t12;
t14 = t6.*1.695744383818896e+2;
t9 = q6+t7;
t10 = sin(t7);
t15 = -t14;
t16 = t8.*3.81283500425112e+1;
t11 = sin(t9);
t17 = t10.*1.0803588359751e+1;
t18 = -t16;
t19 = -t17;
t20 = t11.*1.182334625613;
t21 = -t20;
t22 = t19+t21;
t23 = t18+t22;
t24 = t15+t23;
t25 = t13+t24;
dG_dx = reshape([t25-sin(q1).*2.89243372548249e+2,t25,t24,t23,t22,t21,t25,t25,t24,t23,t22,t21,t24,t24,t24,t23,t22,t21,t23,t23,t23,t23,t22,t21,t22,t22,t22,t22,t22,t21,t21,t21,t21,t21,t21,t21],[6,6]);
