function dJ2_q6 = dJ2_q6(in1)
%DJ2_Q6
%    DJ2_Q6 = DJ2_Q6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    22-Jun-2020 13:00:49

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2+q3+q4+q5+q6;
t3 = cos(t2);
t4 = sin(t2);
t5 = t3.*4.5252e-1;
t6 = t4.*4.5252e-1;
t7 = -t5;
dJ2_q6 = reshape([t6,t7,0.0,0.0,0.0,0.0,t6,t7,0.0,0.0,0.0,0.0,t6,t7,0.0,0.0,0.0,0.0,t6,t7,0.0,0.0,0.0,0.0,t6,t7,0.0,0.0,0.0,0.0,t6,t7,0.0,0.0,0.0,0.0],[6,6]);
