function dJ2_q4 = dJ2_q4(in1)
%DJ2_Q4
%    DJ2_Q4 = DJ2_Q4(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    22-Jun-2020 13:00:49

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2+q3+q4;
t3 = cos(t2);
t4 = q5+t2;
t5 = sin(t2);
t6 = q6+t4;
t7 = sin(t4);
t8 = cos(t4);
t18 = t3.*4.38012e-1;
t19 = t5.*4.38012e-1;
t9 = cos(t6);
t10 = sin(t6);
t11 = t8.*4.5252e-1;
t12 = t7.*4.5252e-1;
t20 = -t18;
t21 = -t19;
t13 = -t11;
t14 = -t12;
t15 = t9.*4.5252e-1;
t16 = t10.*4.5252e-1;
t17 = -t15;
t22 = t13+t16+t20;
t23 = t14+t17+t21;
dJ2_q4 = reshape([t22,t23,0.0,0.0,0.0,0.0,t22,t23,0.0,0.0,0.0,0.0,t22,t23,0.0,0.0,0.0,0.0,t22,t23,0.0,0.0,0.0,0.0,t13+t16,t14+t17,0.0,0.0,0.0,0.0,t16,t17,0.0,0.0,0.0,0.0],[6,6]);
