function dJ2_q5 = dJ2_q5(in1)
%DJ2_Q5
%    DJ2_Q5 = DJ2_Q5(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    22-Jun-2020 13:00:49

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2+q3+q4+q5;
t3 = q6+t2;
t4 = sin(t2);
t5 = cos(t2);
t6 = cos(t3);
t7 = sin(t3);
t8 = t5.*4.5252e-1;
t9 = t4.*4.5252e-1;
t10 = -t8;
t11 = -t9;
t12 = t6.*4.5252e-1;
t13 = t7.*4.5252e-1;
t14 = -t12;
t15 = t10+t13;
t16 = t11+t14;
dJ2_q5 = reshape([t15,t16,0.0,0.0,0.0,0.0,t15,t16,0.0,0.0,0.0,0.0,t15,t16,0.0,0.0,0.0,0.0,t15,t16,0.0,0.0,0.0,0.0,t15,t16,0.0,0.0,0.0,0.0,t13,t14,0.0,0.0,0.0,0.0],[6,6]);
