function dJ_q6 = dJ_q6(in1)
%DJ_Q6
%    DJ_Q6 = DJ_Q6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Jun-2020 16:30:48

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2+q3+q4+q5+q6-1.290439793566535;
t3 = q1+q2+q3+q4+q5+q6+2.803565332283614e-1;
t4 = sin(t2);
t5 = sin(t3);
t6 = t4.*2.764744335377143e-1;
t7 = t5.*2.764744335377143e-1;
t8 = -t7;
dJ_q6 = reshape([t6,t8,0.0,0.0,0.0,0.0,t6,t8,0.0,0.0,0.0,0.0,t6,t8,0.0,0.0,0.0,0.0,t6,t8,0.0,0.0,0.0,0.0,t6,t8,0.0,0.0,0.0,0.0,t6,t8,0.0,0.0,0.0,0.0],[6,6]);
