function out1 = hess_grf_ceq_heel79(in1,toe_th,dmax,cmax,k,us,ud)
%HESS_GRF_CEQ_HEEL79
%    OUT1 = HESS_GRF_CEQ_HEEL79(IN1,TOE_TH,DMAX,CMAX,K,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    23-Jun-2020 09:33:20

out1 = 0.0;
