function out1 = hess_grf_ceq_heel818(in1,toe_th,dmax,cmax,k,us,ud)
%HESS_GRF_CEQ_HEEL818
%    OUT1 = HESS_GRF_CEQ_HEEL818(IN1,TOE_TH,DMAX,CMAX,K,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    23-Jun-2020 09:38:53

out1 = 0.0;
