function out1 = hess_grf_ceq_heel314(in1,toe_th,dmax,cmax,k,us,ud)
%HESS_GRF_CEQ_HEEL314
%    OUT1 = HESS_GRF_CEQ_HEEL314(IN1,TOE_TH,DMAX,CMAX,K,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    23-Jun-2020 10:50:12

out1 = 0.0;
