function out1 = hess_grf_ceq_heel516(in1,toe_th,dmax,cmax,k,us,ud)
%HESS_GRF_CEQ_HEEL516
%    OUT1 = HESS_GRF_CEQ_HEEL516(IN1,TOE_TH,DMAX,CMAX,K,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    23-Jun-2020 10:35:32

out1 = 0.0;
