function beta_grf = beta_grf(in1,th)
%BETA_GRF
%    BETA_GRF = BETA_GRF(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-May-2020 16:44:26

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = sin(q1);
t3 = q1+q2;
t7 = th.*4.0e+2;
t4 = cos(t3);
t5 = sin(t3);
t6 = q3+q4+t3;
t8 = t2.*1.72e+2;
t12 = -t7;
t9 = cos(t6);
t10 = q5+t6;
t11 = sin(t6);
t16 = t4.*(2.0./5.0);
t17 = t5.*(2.0./5.0);
t18 = t5.*1.6e+2;
t13 = q6+t10;
t14 = sin(t10);
t15 = cos(t10);
t20 = t9.*(2.0./5.0);
t21 = t11.*(2.0./5.0);
t22 = t11.*1.6e+2;
t19 = sin(t13);
t23 = t14.*1.72e+2;
t25 = t15.*(4.3e+1./1.0e+2);
t26 = t14.*(4.3e+1./1.0e+2);
t24 = t19.*1.04e+2;
t27 = t20+t25;
t28 = t21+t26;
t29 = t8+t12+t18+t22+t23+t24;
t30 = tanh(t29);
t31 = t30.*(2.0./5.0);
t32 = t31-2.0./5.0;
t33 = t28.*t32;
t34 = t27.*t32;
t35 = -t34;
beta_grf = reshape([t32.*(t2.*(4.3e+1./1.0e+2)+t17+t28),t32.*(t17+t28),t33,t33,t26.*t32,0.0,-t32.*(t16+t27+cos(q1).*(4.3e+1./1.0e+2)),-t32.*(t16+t27),t35,t35,t15.*t32.*(-4.3e+1./1.0e+2),0.0],[6,2]);
