function beta_grf_toe = beta_grf_toe(in1,th)
%BETA_GRF_TOE
%    BETA_GRF_TOE = BETA_GRF_TOE(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-May-2020 14:41:01

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = sin(q1);
t3 = q1+q2;
t7 = atan(7.0./2.6e+1);
t8 = th.*4.0e+2;
t10 = sqrt(2.9e+1);
t4 = cos(t3);
t5 = sin(t3);
t6 = q3+q4+t3;
t9 = t2.*1.72e+2;
t14 = -t8;
t11 = cos(t6);
t12 = q5+t6;
t13 = sin(t6);
t17 = t4.*(2.0./5.0);
t18 = t5.*(2.0./5.0);
t19 = t5.*1.6e+2;
t15 = sin(t12);
t16 = cos(t12);
t20 = t11.*(2.0./5.0);
t21 = t13.*(2.0./5.0);
t22 = t13.*1.6e+2;
t24 = q6+t7+t12;
t29 = q6+t12+2.629947316809195e-1;
t23 = t15.*1.72e+2;
t25 = sin(t24);
t26 = t16.*(4.3e+1./1.0e+2);
t27 = t15.*(4.3e+1./1.0e+2);
t30 = cos(t29);
t31 = sin(t29);
t28 = t10.*t25.*2.0e+1;
t32 = (t10.*t30)./2.0e+1;
t33 = (t10.*t31)./2.0e+1;
t34 = t9+t14+t19+t22+t23+t28;
t38 = t20+t26+t32;
t39 = t21+t27+t33;
t35 = tanh(t34);
t36 = t35./2.0;
t37 = t36-1.0./2.0;
t40 = t37.*t38;
t41 = t37.*t39;
t42 = -t40;
beta_grf_toe = reshape([t37.*(t2.*(4.3e+1./1.0e+2)+t18+t39),t37.*(t18+t39),t41,t41,t37.*(t27+t33),(t10.*t37.*cos(q6+t12-1.307801595113977))./2.0e+1,-t37.*(t17+t38+cos(q1).*(4.3e+1./1.0e+2)),-t37.*(t17+t38),t42,t42,-t37.*(t26+t32),t10.*t30.*t37.*(-1.0./2.0e+1)],[6,2]);
