function dbeta_ank_dx5 = dbeta_ank_dx5(in1,th)
%DBETA_ANK_DX5
%    DBETA_ANK_DX5 = DBETA_ANK_DX5(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-May-2020 21:44:53

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
t2 = sin(q1);
t3 = q1+q2;
t7 = th.*4.0e+2;
t4 = cos(t3);
t5 = sin(t3);
t6 = q3+q4+t3;
t8 = t2.*1.72e+2;
t12 = -t7;
t9 = cos(t6);
t10 = q5+t6;
t11 = sin(t6);
t15 = t4.*(2.0./5.0);
t16 = t5.*(2.0./5.0);
t17 = t5.*1.6e+2;
t13 = sin(t10);
t14 = cos(t10);
t18 = t9.*(2.0./5.0);
t19 = t11.*(2.0./5.0);
t20 = t11.*1.6e+2;
t21 = t13.*1.72e+2;
t22 = t14.*(4.3e+1./1.0e+2);
t23 = t13.*(4.3e+1./1.0e+2);
t24 = t18+t22;
t25 = t19+t23;
t26 = t8+t12+t17+t20+t21;
t27 = tanh(t26);
t28 = t27.^2;
t29 = t27./2.0;
t30 = t28-1.0;
t31 = t29-1.0./2.0;
t32 = t22.*t31;
t33 = t23.*t31;
t34 = t14.*t24.*t30.*8.6e+1;
t35 = t14.*t25.*t30.*8.6e+1;
t36 = -t35;
t37 = t33+t34;
t38 = t32+t36;
dbeta_ank_dx5 = reshape([t32-t14.*t30.*(t2.*(4.3e+1./1.0e+2)+t16+t25).*8.6e+1,t32-t14.*t30.*(t16+t25).*8.6e+1,t38,t38,t32-t13.*t14.*t30.*3.698e+1,0.0,t33+t14.*t30.*(t15+t24+cos(q1).*(4.3e+1./1.0e+2)).*8.6e+1,t33+t14.*t30.*(t15+t24).*8.6e+1,t37,t37,t33+t14.^2.*t30.*3.698e+1,0.0],[6,2]);
