function dbeta_ank_dx6 = dbeta_ank_dx6(in1,th)
%DBETA_ANK_DX6
%    DBETA_ANK_DX6 = DBETA_ANK_DX6(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-May-2020 21:44:53

dbeta_ank_dx6 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,2]);
