function dbeta_heel_dx6 = dbeta_heel_dx6(in1,th)
%DBETA_HEEL_DX6
%    DBETA_HEEL_DX6 = DBETA_HEEL_DX6(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-May-2020 03:26:28

dbeta_heel_dx6 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,2]);
