function dMext_ank_dx6 = dMext_ank_dx6(in1)
%DMEXT_ANK_DX6
%    DMEXT_ANK_DX6 = DMEXT_ANK_DX6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-May-2020 21:44:48

dMext_ank_dx6 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,6]);
