function dMext_dx6 = dMext_dx6(in1)
%DMEXT_DX6
%    DMEXT_DX6 = DMEXT_DX6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    05-May-2020 16:44:26

dMext_dx6 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,6]);
