function dMext_heel_dx6 = dMext_heel_dx6(in1)
%DMEXT_HEEL_DX6
%    DMEXT_HEEL_DX6 = DMEXT_HEEL_DX6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    17-May-2020 04:48:27

dMext_heel_dx6 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[2,6]);
