function Tau_heel = Tau_heel(in1,in2)
%TAU_HEEL
%    TAU_HEEL = TAU_HEEL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    26-Jul-2020 19:31:23

Fx = in2(:,1);
Fy = in2(:,2);
q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t13 = atan(5.145162352941177e-1);
t14 = atan(1.943573266309781);
t19 = 7.878221328233238e+18;
t3 = cos(t2);
t4 = sin(t2);
t5 = q_t3+q_t4+t2;
t20 = -t14;
t6 = cos(t5);
t7 = q_t5+t5;
t8 = sin(t5);
t11 = t3.*4.453122e-1;
t12 = t4.*4.453122e-1;
t9 = sin(t7);
t10 = cos(t7);
t15 = t6.*4.453122e-1;
t16 = t8.*4.453122e-1;
t21 = q_t6+t7+t13;
t23 = q_t6+t7+t20;
t17 = t10.*4.60062e-1;
t18 = t9.*4.60062e-1;
t22 = cos(t21);
t24 = cos(t23);
t25 = (t19.*t22)./9.007199254740992e+19;
t26 = (t19.*t24)./9.007199254740992e+19;
t27 = -t26;
t28 = t16+t18+t25;
t29 = Fx.*t28;
t30 = t15+t17+t27;
t31 = -t29;
t32 = Fy.*t30;
t33 = t31+t32;
Tau_heel = [Fy.*(t11+t30+cos(q_t1).*4.60062e-1)-Fx.*(t12+t28+sin(q_t1).*4.60062e-1);-Fx.*(t12+t28)+Fy.*(t11+t30);t33;t33;-Fx.*(t18+t25)+Fy.*(t17+t27);Fx.*t19.*t22.*(-1.110223024625157e-20)-(Fy.*t19.*t24)./9.007199254740992e+19];
