function dsigma_dq = dsigma_dq(q1,q2,q3,q4,q5,th)
%DSIGMA_DQ
%    DSIGMA_DQ = DSIGMA_DQ(Q1,Q2,Q3,Q4,Q5,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    24-Apr-2020 12:32:12

t2 = sin(q1);
t3 = q1+q2;
t7 = th.*4.0e+2;
t4 = cos(t3);
t5 = sin(t3);
t6 = q3+q4+t3;
t8 = t2.*1.72e+2;
t12 = -t7;
t9 = cos(t6);
t10 = q5+t6;
t11 = sin(t6);
t15 = t4.*1.6e+2;
t16 = t5.*1.6e+2;
t13 = sin(t10);
t14 = cos(t10);
t17 = t9.*1.6e+2;
t18 = t11.*1.6e+2;
t19 = t14.*1.72e+2;
t20 = t13.*1.72e+2;
t21 = t17+t19;
t22 = t8+t12+t16+t18+t20;
t23 = tanh(t22);
t24 = t23.^2;
t25 = t24-1.0;
t26 = t21.*t25.*(2.0./5.0);
dsigma_dq = [t25.*(t15+t21+cos(q1).*1.72e+2).*(2.0./5.0);t25.*(t15+t21).*(2.0./5.0);t26;t26;t14.*t25.*(3.44e+2./5.0)];
