function sigma = sigma_out(q1,q2,q3,q4,q5,th)
%SIGMA_OUT
%    SIGMA = SIGMA_OUT(Q1,Q2,Q3,Q4,Q5,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    24-Apr-2020 12:32:12

t2 = q1+q2;
t3 = q3+q4+t2;
sigma = tanh(th.*-4.0e+2+sin(q5+t3).*1.72e+2+sin(q1).*1.72e+2+sin(t2).*1.6e+2+sin(t3).*1.6e+2).*(-2.0./5.0)+2.0./5.0;
