function Grf_c2 = Grf_c2(in1,us)
%GRF_C2
%    GRF_C2 = GRF_C2(IN1,US)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Jul-2020 11:59:12

Fx = in1(:,1);
Fy = in1(:,2);
Grf_c2 = Fx.^2-Fy.^2.*us.^2;
