function dsigma_knee = dsigma_knee(q2)
%DSIGMA_KNEE
%    DSIGMA_KNEE = DSIGMA_KNEE(Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    21-May-2020 09:35:42

dsigma_knee = tanh(q2.*2.5e+2-pi.*(2.5e+1./3.6e+1)).^2.*1.25e+2-1.25e+2;
