function sigma_knee = sigma_knee(q2)
%SIGMA_KNEE
%    SIGMA_KNEE = SIGMA_KNEE(Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    21-May-2020 09:35:34

sigma_knee = tanh(q2.*2.5e+2-pi.*(2.5e+1./3.6e+1)).*(-1.0./2.0)+1.0./2.0;
