function dJ2_q2 = dJ2_q2(in1)
%DJ2_Q2
%    DJ2_Q2 = DJ2_Q2(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Jun-2020 15:01:57

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = q3+q4+t2;
t6 = cos(t5);
t7 = q5+t5;
t8 = sin(t5);
t15 = t3.*4.38012e-1;
t16 = t4.*4.38012e-1;
t9 = sin(t7);
t10 = cos(t7);
t17 = -t15;
t18 = -t16;
t19 = t6.*4.38012e-1;
t20 = t8.*4.38012e-1;
t11 = t10.*5.2902e-1;
t12 = t9.*5.2902e-1;
t21 = -t19;
t22 = -t20;
t13 = -t11;
t14 = -t12;
t23 = t13+t21;
t24 = t14+t22;
t25 = t17+t23;
t26 = t18+t24;
dJ2_q2 = reshape([t25,t26,0.0,0.0,0.0,0.0,t25,t26,0.0,0.0,0.0,0.0,t23,t24,0.0,0.0,0.0,0.0,t23,t24,0.0,0.0,0.0,0.0,t13,t14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
