function dJ2_q6 = dJ2_q6(in1)
%DJ2_Q6
%    DJ2_Q6 = DJ2_Q6(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Jun-2020 12:16:45

dJ2_q6 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
