function dJ2_q5 = dJ2_q5(in1)
%DJ2_Q5
%    DJ2_Q5 = DJ2_Q5(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Jun-2020 22:29:49

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
t2 = q1+q2+q3+q4+q5;
t3 = sin(t2);
t4 = cos(t2);
t5 = t4.*5.2902e-1;
t6 = t3.*5.2902e-1;
t7 = -t5;
t8 = -t6;
dJ2_q5 = reshape([t7,t8,0.0,0.0,0.0,0.0,t7,t8,0.0,0.0,0.0,0.0,t7,t8,0.0,0.0,0.0,0.0,t7,t8,0.0,0.0,0.0,0.0,t7,t8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
