function dM_dx6 = dM_dx6(q2,q3,q4,q5,q6)
%DM_DX6
%    DM_DX6 = DM_DX6(Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-May-2020 15:23:44

t2 = sin(q6);
t3 = q5+q6;
t4 = sin(t3);
t5 = q3+q4+t3;
t9 = t2.*6.36215097375e-3;
t10 = t2.*1.27243019475e-2;
t6 = q2+t5;
t7 = sin(t5);
t11 = t4.*5.97578553e-3;
t12 = t4.*1.195157106e-2;
t13 = -t10;
t14 = -t9;
t8 = sin(t6);
t15 = -t12;
t16 = -t11;
t17 = t7.*5.97578553e-3;
t18 = t7.*1.195157106e-2;
t19 = -t18;
t20 = -t17;
t21 = t8.*6.36215097375e-3;
t23 = t13+t15;
t24 = t13+t16;
t25 = t14+t16;
t22 = -t21;
t26 = t20+t23;
t27 = t20+t24;
t28 = t20+t25;
t29 = t19+t22+t23;
t30 = t22+t26;
t31 = t22+t27;
t32 = t22+t28;
dM_dx6 = reshape([t8.*(-1.27243019475e-2)+t19+t23,t29,t30,t30,t31,t32,t29,t19+t23,t26,t26,t27,t28,t30,t26,t23,t23,t24,t25,t30,t26,t23,t23,t24,t25,t31,t27,t24,t24,t13,t14,t32,t28,t25,t25,t14,0.0],[6,6]);
