function tt = tt_test(in1,th)
%TT_TEST
%    TT = TT_TEST(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    21-Apr-2020 12:44:10

x1 = in1(:,1);
x2 = in1(:,2);
x3 = in1(:,3);
x4 = in1(:,4);
x5 = in1(:,5);
t2 = x1+x2;
t3 = t2+x3+x4;
tt = tanh(th.*-4.0e+2+sin(t3+x5).*1.8e+2+sin(t2).*1.8e+2+sin(t3).*1.8e+2+sin(x1).*1.8e+2).*(-2.0./5.0)+2.0./5.0;
