function dFn_toe_c3 = dFn_toe_c3(Fy_toe,s_toe)
%DFN_TOE_C3
%    DFN_TOE_C3 = DFN_TOE_C3(FY_TOE,S_TOE)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    25-Jun-2020 23:39:08

dFn_toe_c3 = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;s_toe;0.0;0.0;Fy_toe;0.0];
