function dFn_heel_c3 = dFn_heel_c3(Fy_heel,s_heel)
%DFN_HEEL_C3
%    DFN_HEEL_C3 = DFN_HEEL_C3(FY_HEEL,S_HEEL)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    25-Jun-2020 23:39:08

dFn_heel_c3 = [0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;Fy_heel];
