function dFs_heel_c1_6 = dFs_heel_c1_6(in1,in2,us,ud)
%DFS_HEEL_C1_6
%    DFS_HEEL_C1_6 = DFS_HEEL_C1_6(IN1,IN2,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    22-Jun-2020 13:33:51

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
qd1 = in1(:,7);
qd2 = in1(:,8);
qd3 = in1(:,9);
qd4 = in1(:,10);
qd5 = in1(:,11);
qd6 = in1(:,12);
t2 = sin(q1);
t3 = q1+q2;
t5 = -us;
t4 = sin(t3);
t6 = q3+q4+t3;
t9 = t5+ud;
t14 = t2.*4.5252e-1;
t7 = q5+t6;
t8 = sin(t6);
t24 = t4.*4.38012e-1;
t10 = q6+t7;
t11 = sin(t7);
t26 = t8.*4.38012e-1;
t12 = cos(t10);
t13 = sin(t10);
t22 = t11.*4.5252e-1;
t15 = qd6.*t12.*4.5252e+1;
t16 = qd1.*t13.*4.5252e+1;
t17 = qd2.*t13.*4.5252e+1;
t18 = qd3.*t13.*4.5252e+1;
t19 = qd4.*t13.*4.5252e+1;
t20 = qd5.*t13.*4.5252e+1;
t21 = qd6.*t13.*4.5252e+1;
t23 = t12.*4.5252e-1;
t25 = t22+t23;
t31 = t16+t17+t18+t19+t20+t21;
t27 = qd5.*t25.*1.0e+2;
t28 = t25+t26;
t29 = qd3.*t28.*1.0e+2;
t30 = qd4.*t28.*1.0e+2;
t32 = t24+t28;
t33 = qd2.*t32.*1.0e+2;
t34 = t14+t32;
t35 = qd1.*t34.*1.0e+2;
t36 = t15+t27+t29+t30+t33+t35+5.0;
t38 = t15+t27+t29+t30+t33+t35-5.0;
t37 = tanh(t36);
t39 = tanh(t38);
dFs_heel_c1_6 = t9.*((t31.*(t37.^2-1.0))./2.0-(t31.*(t39.^2-1.0))./2.0).*(us+t9.*(t37.*(-1.0./2.0)+t39./2.0+1.0)).*2.0;
