function dFs_toe_c1_12 = dFs_toe_c1_12(in1,in2,us,ud)
%DFS_TOE_C1_12
%    DFS_TOE_C1_12 = DFS_TOE_C1_12(IN1,IN2,S_TOE,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Jun-2020 13:53:50

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
qd1 = in1(:,7);
qd2 = in1(:,8);
qd3 = in1(:,9);
qd4 = in1(:,10);
qd5 = in1(:,11);
qd6 = in1(:,12);
t2 = sin(q1);
t3 = q1+q2;
t5 = -us;
t4 = sin(t3);
t6 = q3+q4+t3;
t9 = t5+ud;
t11 = t2.*4.5252e-1;
t7 = q5+t6;
t8 = sin(t6);
t13 = t4.*4.38012e-1;
t10 = sin(t7);
t14 = q6+t7-1.290439793566535;
t15 = t8.*4.38012e-1;
t12 = t10.*4.5252e-1;
t16 = cos(t14);
t17 = qd6.*t16.*2.764744335377143e+1;
t18 = t16.*2.764744335377143e-1;
t19 = t12+t18;
t20 = qd5.*t19.*1.0e+2;
t21 = t15+t19;
t22 = qd3.*t21.*1.0e+2;
t23 = qd4.*t21.*1.0e+2;
t24 = t13+t21;
t25 = qd2.*t24.*1.0e+2;
t26 = t11+t24;
t27 = qd1.*t26.*1.0e+2;
t28 = t17+t20+t22+t23+t25+t27+5.0;
t29 = t17+t20+t22+t23+t25+t27-5.0;
t30 = tanh(t28);
t31 = tanh(t29);
dFs_toe_c1_12 = t9.*(us+t9.*(t30.*(-1.0./2.0)+t31./2.0+1.0)).*(t16.*(t30.^2-1.0).*1.382372167688572e+1-t16.*(t31.^2-1.0).*1.382372167688572e+1).*-2.0;
