function dFs_heel_c1_22 = dFs_heel_c1_22(in1,in2,us,ud)
%DFS_HEEL_C1_22
%    DFS_HEEL_C1_22 = DFS_HEEL_C1_22(IN1,IN2,S_HEEL,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Jun-2020 13:54:02

Fy_heel = in2(:,2);
dFs_heel_c1_22 = Fy_heel.*-2.0;
