function dFs_heel_c1_7 = dFs_heel_c1_7(in1,in2,us,ud)
%DFS_HEEL_C1_7
%    DFS_HEEL_C1_7 = DFS_HEEL_C1_7(IN1,IN2,S_HEEL,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Jun-2020 13:54:02

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
qd1 = in1(:,7);
qd2 = in1(:,8);
qd3 = in1(:,9);
qd4 = in1(:,10);
qd5 = in1(:,11);
qd6 = in1(:,12);
t2 = sin(q1);
t3 = q1+q2;
t5 = -us;
t4 = sin(t3);
t6 = q3+q4+t3;
t9 = t5+ud;
t13 = t2.*4.5252e+1;
t14 = t2.*4.5252e-1;
t7 = q5+t6;
t8 = sin(t6);
t20 = t4.*4.38012e-1;
t21 = t4.*4.38012e+1;
t10 = q6+t7;
t11 = sin(t7);
t23 = t8.*4.38012e-1;
t24 = t8.*4.38012e+1;
t12 = cos(t10);
t15 = t11.*4.5252e+1;
t18 = t11.*4.5252e-1;
t16 = t12.*4.5252e+1;
t19 = t12.*4.5252e-1;
t17 = qd6.*t16;
t22 = t18+t19;
t31 = t13+t15+t16+t21+t24;
t25 = qd5.*t22.*1.0e+2;
t26 = t22+t23;
t27 = qd3.*t26.*1.0e+2;
t28 = qd4.*t26.*1.0e+2;
t29 = t20+t26;
t30 = qd2.*t29.*1.0e+2;
t32 = t14+t29;
t33 = qd1.*t32.*1.0e+2;
t34 = t17+t25+t27+t28+t30+t33+5.0;
t36 = t17+t25+t27+t28+t30+t33-5.0;
t35 = tanh(t34);
t37 = tanh(t36);
dFs_heel_c1_7 = t9.*((t31.*(t35.^2-1.0))./2.0-(t31.*(t37.^2-1.0))./2.0).*(us+t9.*(t35.*(-1.0./2.0)+t37./2.0+1.0)).*-2.0;
