function dFs_heel_c1_21 = dFs_heel_c1_21(in1,in2,us,ud)
%DFS_HEEL_C1_21
%    DFS_HEEL_C1_21 = DFS_HEEL_C1_21(IN1,IN2,S_HEEL,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Jun-2020 13:54:00

Fx_heel = in2(:,1);
dFs_heel_c1_21 = Fx_heel.*2.0;
