function dFs_toe_c1_23 = dFs_toe_c1_23(in1,in2,us,ud)
%DFS_TOE_C1_23
%    DFS_TOE_C1_23 = DFS_TOE_C1_23(IN1,IN2,S_TOE,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Jun-2020 14:56:53

dFs_toe_c1_23 = 0.0;
