function dFs_heel_c1_24 = dFs_heel_c1_24(in1,in2,us,ud)
%DFS_HEEL_C1_24
%    DFS_HEEL_C1_24 = DFS_HEEL_C1_24(IN1,IN2,S_HEEL,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Jun-2020 13:54:01

dFs_heel_c1_24 = 0.0;
