function dFs_toe_c1_10 = dFs_toe_c1_10(in1,in2,us,ud)
%DFS_TOE_C1_10
%    DFS_TOE_C1_10 = DFS_TOE_C1_10(IN1,IN2,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    22-Jun-2020 14:48:56

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
qd1 = in1(:,7);
qd2 = in1(:,8);
qd3 = in1(:,9);
qd4 = in1(:,10);
qd5 = in1(:,11);
qd6 = in1(:,12);
t2 = sin(q1);
t3 = q1+q2;
t5 = -us;
t4 = sin(t3);
t6 = q3+q4+t3;
t9 = t5+ud;
t11 = t2.*4.5252e-1;
t7 = q5+t6;
t8 = sin(t6);
t14 = t4.*4.38012e-1;
t10 = sin(t7);
t15 = q6+t7-1.290439793566535;
t16 = t8.*4.38012e-1;
t17 = t8.*4.38012e+1;
t12 = t10.*4.5252e+1;
t13 = t10.*4.5252e-1;
t18 = cos(t15);
t19 = t18.*2.764744335377143e+1;
t21 = t18.*2.764744335377143e-1;
t20 = qd6.*t19;
t22 = t13+t21;
t24 = t12+t17+t19;
t23 = qd5.*t22.*1.0e+2;
t25 = t16+t22;
t26 = qd3.*t25.*1.0e+2;
t27 = qd4.*t25.*1.0e+2;
t28 = t14+t25;
t29 = qd2.*t28.*1.0e+2;
t30 = t11+t28;
t31 = qd1.*t30.*1.0e+2;
t32 = t20+t23+t26+t27+t29+t31+5.0;
t33 = t20+t23+t26+t27+t29+t31-5.0;
t34 = tanh(t32);
t35 = tanh(t33);
dFs_toe_c1_10 = t9.*((t24.*(t34.^2-1.0))./2.0-(t24.*(t35.^2-1.0))./2.0).*(us+t9.*(t34.*(-1.0./2.0)+t35./2.0+1.0)).*-2.0;
