function dFs_heel_c1_9 = dFs_heel_c1_9(in1,in2,us,ud)
%DFS_HEEL_C1_9
%    DFS_HEEL_C1_9 = DFS_HEEL_C1_9(IN1,IN2,S_HEEL,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Jun-2020 13:54:02

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
qd1 = in1(:,7);
qd2 = in1(:,8);
qd3 = in1(:,9);
qd4 = in1(:,10);
qd5 = in1(:,11);
qd6 = in1(:,12);
t2 = sin(q1);
t3 = q1+q2;
t5 = -us;
t4 = sin(t3);
t6 = q3+q4+t3;
t9 = t5+ud;
t13 = t2.*4.5252e-1;
t7 = q5+t6;
t8 = sin(t6);
t19 = t4.*4.38012e-1;
t10 = q6+t7;
t11 = sin(t7);
t21 = t8.*4.38012e-1;
t22 = t8.*4.38012e+1;
t12 = cos(t10);
t14 = t11.*4.5252e+1;
t17 = t11.*4.5252e-1;
t15 = t12.*4.5252e+1;
t18 = t12.*4.5252e-1;
t16 = qd6.*t15;
t20 = t17+t18;
t24 = t14+t15+t22;
t23 = qd5.*t20.*1.0e+2;
t25 = t20+t21;
t26 = qd3.*t25.*1.0e+2;
t27 = qd4.*t25.*1.0e+2;
t28 = t19+t25;
t29 = qd2.*t28.*1.0e+2;
t30 = t13+t28;
t31 = qd1.*t30.*1.0e+2;
t32 = t16+t23+t26+t27+t29+t31+5.0;
t34 = t16+t23+t26+t27+t29+t31-5.0;
t33 = tanh(t32);
t35 = tanh(t34);
dFs_heel_c1_9 = t9.*((t24.*(t33.^2-1.0))./2.0-(t24.*(t35.^2-1.0))./2.0).*(us+t9.*(t33.*(-1.0./2.0)+t35./2.0+1.0)).*-2.0;
