function dFs_heel_c1_12 = dFs_heel_c1_12(in1,in2,us,ud)
%DFS_HEEL_C1_12
%    DFS_HEEL_C1_12 = DFS_HEEL_C1_12(IN1,IN2,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Jun-2020 02:29:44

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
qd1 = in1(:,7);
qd2 = in1(:,8);
qd3 = in1(:,9);
qd4 = in1(:,10);
qd5 = in1(:,11);
qd6 = in1(:,12);
t2 = sin(q1);
t3 = q1+q2;
t5 = -us;
t4 = sin(t3);
t6 = q3+q4+t3;
t9 = t5+ud;
t13 = t2.*4.5252e-1;
t7 = q5+t6;
t8 = sin(t6);
t17 = t4.*4.38012e-1;
t10 = q6+t7;
t11 = sin(t7);
t19 = t8.*4.38012e-1;
t12 = cos(t10);
t15 = t11.*4.5252e-1;
t14 = qd6.*t12.*4.5252e+1;
t16 = t12.*4.5252e-1;
t18 = t15+t16;
t20 = qd5.*t18.*1.0e+2;
t21 = t18+t19;
t22 = qd3.*t21.*1.0e+2;
t23 = qd4.*t21.*1.0e+2;
t24 = t17+t21;
t25 = qd2.*t24.*1.0e+2;
t26 = t13+t24;
t27 = qd1.*t26.*1.0e+2;
t28 = t14+t20+t22+t23+t25+t27+5.0;
t30 = t14+t20+t22+t23+t25+t27-5.0;
t29 = tanh(t28);
t31 = tanh(t30);
dFs_heel_c1_12 = t9.*(t12.*(t29.^2-1.0).*2.2626e+1-t12.*(t31.^2-1.0).*2.2626e+1).*(us+t9.*(t29.*(-1.0./2.0)+t31./2.0+1.0)).*-2.0;
