function dFs_toe_c1_8 = dFs_toe_c1_8(in1,in2,us,ud)
%DFS_TOE_C1_8
%    DFS_TOE_C1_8 = DFS_TOE_C1_8(IN1,IN2,S_TOE,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Jun-2020 15:02:52

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
qd1 = in1(:,7);
qd2 = in1(:,8);
qd3 = in1(:,9);
qd4 = in1(:,10);
qd5 = in1(:,11);
qd6 = in1(:,12);
t2 = sin(q1);
t3 = q1+q2;
t5 = -us;
t4 = sin(t3);
t6 = q3+q4+t3;
t9 = t5+ud;
t11 = t2.*4.5252e-1;
t7 = q5+t6;
t8 = sin(t6);
t14 = t4.*4.38012e-1;
t15 = t4.*4.38012e+1;
t10 = sin(t7);
t16 = q6+t7-1.290439793566535;
t17 = t8.*4.38012e-1;
t18 = t8.*4.38012e+1;
t12 = t10.*4.5252e+1;
t13 = t10.*4.5252e-1;
t19 = cos(t16);
t20 = t19.*2.764744335377143e+1;
t22 = t19.*2.764744335377143e-1;
t21 = qd6.*t20;
t23 = t13+t22;
t28 = t12+t15+t18+t20;
t24 = qd5.*t23.*1.0e+2;
t25 = t17+t23;
t26 = qd3.*t25.*1.0e+2;
t27 = qd4.*t25.*1.0e+2;
t29 = t14+t25;
t30 = qd2.*t29.*1.0e+2;
t31 = t11+t29;
t32 = qd1.*t31.*1.0e+2;
t33 = t21+t24+t26+t27+t30+t32+5.0;
t34 = t21+t24+t26+t27+t30+t32-5.0;
t35 = tanh(t33);
t36 = tanh(t34);
dFs_toe_c1_8 = t9.*((t28.*(t35.^2-1.0))./2.0-(t28.*(t36.^2-1.0))./2.0).*(us+t9.*(t35.*(-1.0./2.0)+t36./2.0+1.0)).*-2.0;
