function Fn_heel_c3 = Fn_heel_c3(Fy_heel,s_heel)
%FN_HEEL_C3
%    FN_HEEL_C3 = FN_HEEL_C3(FY_HEEL,S_HEEL)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    25-Jun-2020 23:39:08

Fn_heel_c3 = Fy_heel.*s_heel;
