function Fn_toe_ceq1 = Fn_toe_ceq1(in1,in2,th,k,cmax,dmax)
%FN_TOE_CEQ1
%    FN_TOE_CEQ1 = FN_TOE_CEQ1(IN1,IN2,TH,K,CMAX,DMAX)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    22-Jun-2020 13:33:45

Fy_toe = in2(:,2);
q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
qd1 = in1(:,7);
qd2 = in1(:,8);
qd3 = in1(:,9);
qd4 = in1(:,10);
qd5 = in1(:,11);
qd6 = in1(:,12);
t2 = sin(q1);
t3 = q1+q2;
t6 = 1.0./dmax;
t7 = -th;
t14 = atan(3.472941176470588);
t15 = 1.535969075209524e+3;
t4 = cos(t3);
t5 = sin(t3);
t8 = q3+q4+t3;
t16 = -t14;
t17 = t2.*4.5252e-1;
t9 = cos(t8);
t10 = q5+t8;
t11 = sin(t8);
t22 = t4.*4.38012e-1;
t23 = t5.*4.38012e-1;
t12 = sin(t10);
t13 = cos(t10);
t20 = q6+t10+t16;
t25 = q6+t10+2.803565332283614e-1;
t26 = t9.*4.38012e-1;
t27 = t11.*4.38012e-1;
t18 = t13.*4.5252e-1;
t19 = t12.*4.5252e-1;
t21 = cos(t20);
t28 = cos(t25);
t24 = t15.*t21.*1.8e-4;
t29 = t28.*2.764744335377143e-1;
t30 = t18+t26+t29;
t31 = t7+t17+t19+t23+t24+t27;
Fn_toe_ceq1 = Fy_toe+(k.*t31.^2-cmax.*t6.*t31.*(tanh(t6.*(t2.*9.0504e-1+t5.*8.76024e-1+t11.*8.76024e-1+t12.*9.0504e-1-th.*2.0+t15.*t21.*3.6e-4))./2.0-1.0./2.0).*(qd5.*(t18+t29)+qd2.*(t22+t30)+qd3.*t30+qd4.*t30+qd6.*t29+qd1.*(t22+t30+cos(q1).*4.5252e-1))).*(tanh(t2.*1.81008e+2+t5.*1.752048e+2+t11.*1.752048e+2+t12.*1.81008e+2-th.*4.0e+2+t15.*t21.*(9.0./1.25e+2))./2.0-1.0./2.0);
