function Fn_toe_c3 = Fn_toe_c3(Fy_toe,s_toe)
%FN_TOE_C3
%    FN_TOE_C3 = FN_TOE_C3(FY_TOE,S_TOE)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    25-Jun-2020 23:39:08

Fn_toe_c3 = Fy_toe.*s_toe;
