function Fs_toe_c2 = Fs_toe_c2(in1,Fx_toe)
%FS_TOE_C2
%    FS_TOE_C2 = FS_TOE_C2(IN1,FX_TOE)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    25-Jun-2020 12:39:53

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
qd1 = in1(:,7);
qd2 = in1(:,8);
qd3 = in1(:,9);
qd4 = in1(:,10);
qd5 = in1(:,11);
qd6 = in1(:,12);
t2 = q1+q2;
t3 = sin(t2);
t4 = q3+q4+t2;
t5 = q5+t4;
t6 = sin(t4);
t9 = t3.*4.38012e-1;
t7 = sin(t5);
t10 = q6+t5-1.290439793566535;
t11 = t6.*4.38012e-1;
t8 = t7.*4.5252e-1;
t12 = cos(t10);
t13 = t12.*2.764744335377143e-1;
t14 = t8+t11+t13;
Fs_toe_c2 = -Fx_toe.*(qd2.*(t9+t14)+qd5.*(t8+t13)+qd3.*t14+qd4.*t14+qd6.*t13+qd1.*(t9+t14+sin(q1).*4.5252e-1));
