function Fs_toe_c1 = Fs_toe_c1(in1,in2,us,ud)
%FS_TOE_C1
%    FS_TOE_C1 = FS_TOE_C1(IN1,IN2,US,UD)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Jun-2020 02:29:33

Fx_toe = in2(:,1);
Fy_toe = in2(:,2);
q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
qd1 = in1(:,7);
qd2 = in1(:,8);
qd3 = in1(:,9);
qd4 = in1(:,10);
qd5 = in1(:,11);
qd6 = in1(:,12);
t2 = sin(q1);
t3 = q1+q2;
t4 = sin(t3);
t5 = q3+q4+t3;
t9 = t2.*4.5252e-1;
t6 = q5+t5;
t7 = sin(t5);
t11 = t4.*4.38012e-1;
t8 = sin(t6);
t12 = q6+t6-1.290439793566535;
t13 = t7.*4.38012e-1;
t10 = t8.*4.5252e-1;
t14 = cos(t12);
t15 = qd6.*t14.*2.764744335377143e+1;
t16 = t14.*2.764744335377143e-1;
t17 = t10+t16;
t18 = qd5.*t17.*1.0e+2;
t19 = t13+t17;
t20 = qd3.*t19.*1.0e+2;
t21 = qd4.*t19.*1.0e+2;
t22 = t11+t19;
t23 = qd2.*t22.*1.0e+2;
t24 = t9+t22;
t25 = qd1.*t24.*1.0e+2;
Fs_toe_c1 = -(us+(ud-us).*(tanh(t15+t18+t20+t21+t23+t25-5.0)./2.0-tanh(t15+t18+t20+t21+t23+t25+5.0)./2.0+1.0)).^2+Fx_toe.^2-Fy_toe.^2;
