function Tau_toe = Tau_toe(in1,in2)
%TAU_TOE
%    TAU_TOE = TAU_TOE(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    08-Jul-2020 11:04:37

Fx = in2(:,1);
Fy = in2(:,2);
q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t3 = cos(t2);
t4 = sin(t2);
t5 = q_t3+q_t4+t2;
t6 = cos(t5);
t7 = q_t5+t5;
t8 = sin(t5);
t13 = t3.*4.38012e-1;
t14 = t4.*4.38012e-1;
t9 = sin(t7);
t10 = cos(t7);
t15 = q_t6+t7-1.290439793566535;
t16 = q_t6+t7+2.803565332283614e-1;
t17 = t6.*4.38012e-1;
t18 = t8.*4.38012e-1;
t11 = t10.*4.5252e-1;
t12 = t9.*4.5252e-1;
t19 = cos(t15);
t20 = cos(t16);
t21 = t19.*2.764744335377143e-1;
t22 = t20.*2.764744335377143e-1;
t23 = t12+t18+t21;
t24 = t11+t17+t22;
t25 = Fx.*t23;
t26 = Fy.*t24;
t27 = -t25;
t28 = t26+t27;
Tau_toe = [Fy.*(t13+t24+cos(q_t1).*4.5252e-1)-Fx.*(t14+t23+sin(q_t1).*4.5252e-1);-Fx.*(t14+t23)+Fy.*(t13+t24);t28;t28;-Fx.*(t12+t21)+Fy.*(t11+t22);Fx.*t19.*(-2.764744335377143e-1)+Fy.*t22];
