function Irow = inertia_row_5(rob,in2)
%% INERTIA_ROW_5 - Computation of the robot specific inertia matrix row for corresponding to joint 5 of 6. 
% ========================================================================= 
%    
%    Irow = inertia_row_5(rob,q) 
%    Irow = rob.inertia_row_5(q) 
%    
%  Description:: 
%    Given a full set of joint variables this function computes the 
%    inertia matrix row number 5 of 6 for noname. 
%    
%  Input:: 
%    rob: robot object of noname specific class 
%    q:  6-element vector of generalized 
%         coordinates 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    Irow:  [1x6] row of the robot inertia matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also coriolis.
%    
    
% Copyright (C) 1993-2020, by Peter I. Corke 
% Copyright (C) 2012-2020, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2020 06:03:37

q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
t2 = cos(q3);
t3 = cos(q4);
t4 = cos(q5);
t5 = cos(q6);
t6 = sin(q3);
t7 = sin(q4);
t8 = sin(q5);
t9 = sin(q6);
t10 = t9.^2;
t11 = t5.*(2.73e+2./1.0e+3);
t14 = t5.*3.549e-2;
t12 = t9.*t11;
t13 = t10.*(2.73e+2./1.0e+3);
t15 = t10.*7.098e-2;
t16 = t11+1.365e-1;
t17 = t5.*t16;
t18 = t9.*t16;
t19 = -t18;
t20 = t17.*(1.3e+1./5.0e+1);
t22 = -t4.*(t18-t5.*t9.*(2.73e+2./1.0e+3));
t23 = -t8.*(t18-t5.*t9.*(2.73e+2./1.0e+3));
t24 = t4.*(t18-t5.*t9.*(2.73e+2./1.0e+3));
t25 = t8.*(t18-t5.*t9.*(2.73e+2./1.0e+3)).*(-2.0./5.0);
t26 = t13+t17+4.18e+2./6.25e+2;
t21 = t12+t19;
t27 = t8.*t26;
t28 = t4.*t26;
t29 = t28.*(2.0./5.0);
t30 = t23+t28;
t31 = t24+t27;
t32 = t3.*t30;
t33 = t7.*t30;
t34 = t3.*t31;
t35 = t7.*t31;
t37 = t14+t15+t20+t25+t29+1.44817e-1;
t36 = -t35;
t38 = t33+t34;
t39 = t32+t36;
t40 = t6.*t38.*(2.0./5.0);
t41 = -t40;
t42 = t2.*t39.*(2.0./5.0);
Irow = [t37+t41+t42+cos(q2).*(t2.*t39-t6.*t38).*(4.3e+1./1.0e+2)-sin(q2).*(t2.*t38+t6.*t39).*(4.3e+1./1.0e+2),t37+t41+t42,t37,t37,t14+t15+t20+1.44817e-1,t14+1.7745e-2];
