function Irow = inertia_row_3(rob,in2)
%% INERTIA_ROW_3 - Computation of the robot specific inertia matrix row for corresponding to joint 3 of 6. 
% ========================================================================= 
%    
%    Irow = inertia_row_3(rob,q) 
%    Irow = rob.inertia_row_3(q) 
%    
%  Description:: 
%    Given a full set of joint variables this function computes the 
%    inertia matrix row number 3 of 6 for noname. 
%    
%  Input:: 
%    rob: robot object of noname specific class 
%    q:  6-element vector of generalized 
%         coordinates 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    Irow:  [1x6] row of the robot inertia matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also coriolis.
%    
    
% Copyright (C) 1993-2020, by Peter I. Corke 
% Copyright (C) 2012-2020, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2020 06:02:34

q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
t2 = cos(q3);
t3 = cos(q4);
t4 = cos(q5);
t5 = cos(q6);
t6 = sin(q3);
t7 = sin(q4);
t8 = sin(q5);
t9 = sin(q6);
t10 = t4.*(2.0./5.0);
t11 = t5.*t8.*(2.1e+1./5.0e+1);
t12 = t8.*t9.*(2.1e+1./5.0e+1);
t13 = t4.*(1.76e+2./1.25e+2);
t14 = t8.*(1.76e+2./1.25e+2);
t16 = t4.*2.6752e-1;
t18 = t8.*t9.*5.46e-2;
t15 = -t12;
t17 = t10+1.3e+1./5.0e+1;
t19 = -t18;
t20 = t5.*t17.*(2.1e+1./2.0e+1);
t21 = t9.*t17.*(2.1e+1./2.0e+1);
t22 = t5.*t17.*1.365e-1;
t23 = t11+t21;
t27 = t15+t20+1.365e-1;
t24 = t5.*t23;
t25 = t9.*t23;
t28 = t5.*t27;
t29 = t9.*t27;
t26 = t25.*(1.3e+1./5.0e+1);
t30 = -t29;
t31 = t28.*(1.3e+1./5.0e+1);
t35 = t13+t25+t28+4.18e+2./6.25e+2;
t32 = t14+t24+t30;
t37 = t4.*t35;
t38 = t8.*t35;
t40 = t10.*t35;
t33 = t4.*t32;
t34 = t8.*t32;
t39 = -t38;
t36 = t34.*(2.0./5.0);
t41 = t33+t39;
t44 = t34+t37+1.3209;
t42 = t3.*t41;
t43 = t7.*t41;
t45 = t3.*t44;
t46 = t7.*t44;
t47 = -t46;
t50 = t43+t45+1.18117e+1;
t48 = t42+t47;
t51 = t2.*t50.*(2.0./5.0);
t49 = t6.*t48.*(2.0./5.0);
Irow = [t16+t19+t22+t26+t31+t36+t40+t49+t51+cos(q2).*(t2.*t50+t6.*t48).*(4.3e+1./1.0e+2)+sin(q2).*(t2.*t48-t6.*t50).*(4.3e+1./1.0e+2)+3.794763,t16+t19+t22+t26+t31+t36+t40+t49+t51+3.794763,t16+t19+t22+t26+t31+t36+t40+3.794763,t16+t19+t22+t26+t31+t36+t40+3.6937e-1,t16+t19+t22+t26+t31+1.44817e-1,t19+t22+1.7745e-2];
