function Irow = inertia_row_6(rob,in2)
%% INERTIA_ROW_6 - Computation of the robot specific inertia matrix row for corresponding to joint 6 of 6. 
% ========================================================================= 
%    
%    Irow = inertia_row_6(rob,q) 
%    Irow = rob.inertia_row_6(q) 
%    
%  Description:: 
%    Given a full set of joint variables this function computes the 
%    inertia matrix row number 6 of 6 for noname. 
%    
%  Input:: 
%    rob: robot object of noname specific class 
%    q:  6-element vector of generalized 
%         coordinates 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    Irow:  [1x6] row of the robot inertia matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also coriolis.
%    
    
% Copyright (C) 1993-2020, by Peter I. Corke 
% Copyright (C) 2012-2020, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    25-Apr-2020 06:03:38

q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
q6 = in2(:,6);
t2 = cos(q3);
t3 = cos(q4);
t4 = cos(q5);
t5 = cos(q6);
t6 = sin(q3);
t7 = sin(q4);
t8 = sin(q5);
t9 = sin(q6);
t10 = t4.*t5.*1.365e-1;
t11 = t4.*t5.*5.46e-2;
t12 = t4.*t9.*1.365e-1;
t13 = t5.*t8.*1.365e-1;
t14 = t8.*t9.*1.365e-1;
t15 = t8.*t9.*5.46e-2;
t18 = t5.*3.549e-2;
t16 = -t14;
t17 = -t15;
t19 = t12+t13;
t20 = t10+t16;
t21 = t3.*t19;
t22 = t7.*t19;
t26 = t11+t17+t18+1.7745e-2;
t23 = t3.*t20;
t24 = t7.*t20;
t25 = -t22;
t27 = t21+t24;
t28 = t23+t25;
t31 = t2.*(t22-t23).*(-2.0./5.0);
t29 = t6.*t27.*(2.0./5.0);
t30 = -t29;
Irow = [t26+t30+t31-cos(q2).*(t6.*t27+t2.*(t22-t23)).*(4.3e+1./1.0e+2)-sin(q2).*(t2.*t27-t6.*(t22-t23)).*(4.3e+1./1.0e+2),t26+t30+t31,t26,t26,t18+1.7745e-2,1.7745e-2];
