function J_toe = J_toe(in1)
%J_TOE
%    J_TOE = J_TOE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Jul-2020 11:50:56

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t11 = atan(2.87940379403794e-1);
t12 = atan(3.472941176470588);
t13 = 1.535969075209524e+3;
t3 = cos(t2);
t4 = sin(t2);
t5 = q_t3+q_t4+t2;
t14 = -t12;
t6 = cos(t5);
t7 = q_t5+t5;
t8 = sin(t5);
t22 = t3.*4.13678e-1;
t23 = t4.*4.13678e-1;
t9 = sin(t7);
t10 = cos(t7);
t15 = q_t6+t7+t11;
t19 = q_t6+t7+t14;
t24 = -t23;
t26 = t6.*4.13678e-1;
t27 = t8.*4.13678e-1;
t16 = cos(t15);
t17 = t10.*4.2738e-1;
t18 = t9.*4.2738e-1;
t20 = cos(t19);
t28 = -t27;
t21 = -t18;
t25 = t13.*t16.*1.7e-4;
t29 = t13.*t20.*1.7e-4;
t30 = -t29;
t31 = t17+t25+t26;
t32 = t21+t28+t30;
J_toe = reshape([t24+t32-sin(q_t1).*4.2738e-1,t22+t31+cos(q_t1).*4.2738e-1,0.0,t24+t32,t22+t31,0.0,t32,t31,0.0,t32,t31,0.0,t21+t30,t17+t25,0.0,t30,t25,0.0],[3,6]);
