function dsigma_toe = dsigma_toe(in1,th)
%DSIGMA_TOE
%    DSIGMA_TOE = DSIGMA_TOE(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Jun-2020 15:00:21

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = sin(q1);
t3 = q1+q2;
t7 = th.*4.0e+2;
t14 = atan(3.472941176470588);
t15 = 1.535969075209524e+3;
t4 = cos(t3);
t5 = sin(t3);
t6 = q3+q4+t3;
t11 = -t7;
t16 = t2.*1.81008e+2;
t17 = -t14;
t8 = cos(t6);
t9 = q5+t6;
t10 = sin(t6);
t26 = t4.*1.752048e+2;
t27 = t5.*1.752048e+2;
t12 = sin(t9);
t13 = cos(t9);
t20 = q6+t9+t17;
t28 = t10.*1.752048e+2;
t29 = t8.*1.752048e+2;
t18 = t13.*1.81008e+2;
t19 = t12.*1.81008e+2;
t21 = cos(t20);
t22 = sin(t20);
t23 = t15.*t21.*(9.0./1.25e+2);
t24 = t15.*t22.*(9.0./1.25e+2);
t25 = -t24;
t31 = t11+t16+t19+t23+t27+t28;
t30 = t18+t25+t29;
t32 = tanh(t31);
t33 = t32.^2;
t34 = t33-1.0;
t35 = (t30.*t34)./2.0;
dsigma_toe = [(t34.*(t26+t30+cos(q1).*1.81008e+2))./2.0;(t34.*(t26+t30))./2.0;t35;t35;(t34.*(t18+t25))./2.0;t15.*t22.*t34.*(-9.0./2.5e+2)];
