function dsigma_toe = dsigma_toe(in1,th)
%DSIGMA_TOE
%    DSIGMA_TOE = DSIGMA_TOE(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-May-2020 14:55:30

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = sin(q1);
t3 = q1+q2;
t7 = th.*4.0e+2;
t21 = atan(3.488235294117647e-1);
t22 = 2.432562589705372e+17;
t4 = cos(t3);
t5 = sin(t3);
t6 = q3+q4+t3;
t11 = -t7;
t14 = t2.*1.7784e+2;
t23 = -t21;
t8 = cos(t6);
t9 = q5+t6;
t10 = sin(t6);
t15 = t4.*1.6704e+2;
t16 = t5.*1.6704e+2;
t12 = sin(t9);
t13 = cos(t9);
t17 = t8.*1.6704e+2;
t18 = t10.*1.6704e+2;
t24 = q6+t9+t23;
t19 = t13.*1.7784e+2;
t20 = t12.*1.7784e+2;
t25 = cos(t24);
t26 = sin(t24);
t27 = t22.*t25.*1.332267629550188e-16;
t28 = t22.*t26.*1.332267629550188e-16;
t29 = -t28;
t31 = t11+t14+t16+t18+t20+t27;
t30 = t17+t19+t29;
t32 = tanh(t31);
t33 = t32.^2;
t34 = t33-1.0;
t35 = (t30.*t34)./2.0;
dsigma_toe = [(t34.*(t15+t30+cos(q1).*1.7784e+2))./2.0;(t34.*(t15+t30))./2.0;t35;t35;(t34.*(t19+t29))./2.0;t22.*t26.*t34.*(-6.661338147750939e-17)];
