function Tau_heel = Tau_heel(in1,in2)
%TAU_HEEL
%    TAU_HEEL = TAU_HEEL(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-Jul-2020 17:33:53

Fx = in2(:,1);
Fy = in2(:,2);
q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t3 = cos(t2);
t4 = sin(t2);
t5 = q_t3+q_t4+t2;
t6 = cos(t5);
t7 = q_t5+t5;
t8 = sin(t5);
t19 = t3.*4.13678e-1;
t20 = t4.*4.13678e-1;
t9 = q_t6+t7;
t10 = sin(t7);
t11 = cos(t7);
t21 = t6.*4.13678e-1;
t22 = t8.*4.13678e-1;
t12 = cos(t9);
t13 = sin(t9);
t17 = t11.*4.2738e-1;
t18 = t10.*4.2738e-1;
t14 = t12.*7.225e-2;
t15 = t13.*7.225e-2;
t16 = -t15;
t23 = t14+t18+t22;
t24 = t16+t17+t21;
t25 = Fx.*t23;
t26 = Fy.*t24;
t27 = -t25;
t28 = t26+t27;
Tau_heel = [Fy.*(t19+t24+cos(q_t1).*4.2738e-1)-Fx.*(t20+t23+sin(q_t1).*4.2738e-1);-Fx.*(t20+t23)+Fy.*(t19+t24);t28;t28;-Fx.*(t14+t18)+Fy.*(t16+t17);Fx.*t12.*(-7.225e-2)-Fy.*t13.*7.225e-2];
