function J_heel = J_heel(in1)
%J_HEEL
%    J_HEEL = J_HEEL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Jul-2020 22:48:24

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t3 = cos(t2);
t4 = sin(t2);
t5 = q_t3+q_t4+t2;
t6 = cos(t5);
t7 = q_t5+t5;
t8 = sin(t5);
t14 = t3.*4.453122e-1;
t15 = t4.*4.453122e-1;
t9 = q_t6+t7;
t10 = sin(t7);
t11 = cos(t7);
t16 = -t15;
t17 = t6.*4.453122e-1;
t18 = t8.*4.453122e-1;
t12 = cos(t9);
t13 = sin(t9);
t19 = t11.*4.60062e-1;
t20 = t10.*4.60062e-1;
t21 = -t18;
t22 = -t20;
t23 = t12.*4.60062e-1;
t24 = t13.*4.60062e-1;
t25 = -t23;
t26 = -t24;
t27 = t17+t19+t26;
t28 = t21+t22+t25;
J_heel = reshape([t16+t28-sin(q_t1).*4.60062e-1,t14+t27+cos(q_t1).*4.60062e-1,0.0,t16+t28,t14+t27,0.0,t28,t27,0.0,t28,t27,0.0,t22+t25,t19+t26,0.0,t25,t26,0.0],[3,6]);
