function dsigma_toe = dsigma_toe(in1,th)
%DSIGMA_TOE
%    DSIGMA_TOE = DSIGMA_TOE(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    16-May-2020 14:39:01

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = sin(q1);
t3 = q1+q2;
t7 = atan(7.0./2.6e+1);
t8 = th.*4.0e+2;
t10 = sqrt(2.9e+1);
t4 = cos(t3);
t5 = sin(t3);
t6 = q3+q4+t3;
t9 = t2.*1.72e+2;
t14 = -t8;
t11 = cos(t6);
t12 = q5+t6;
t13 = sin(t6);
t17 = t4.*1.6e+2;
t18 = t5.*1.6e+2;
t15 = sin(t12);
t16 = cos(t12);
t19 = t11.*1.6e+2;
t20 = t13.*1.6e+2;
t23 = q6+t7+t12;
t21 = t16.*1.72e+2;
t22 = t15.*1.72e+2;
t24 = cos(t23);
t25 = sin(t23);
t26 = t10.*t24.*2.0e+1;
t27 = t10.*t25.*2.0e+1;
t28 = t19+t21+t26;
t29 = t9+t14+t18+t20+t22+t27;
t30 = tanh(t29);
t31 = t30.^2;
t32 = t31-1.0;
t33 = (t28.*t32)./2.0;
dsigma_toe = [(t32.*(t17+t28+cos(q1).*1.72e+2))./2.0;(t32.*(t17+t28))./2.0;t33;t33;(t32.*(t21+t26))./2.0;t10.*t24.*t32.*1.0e+1];
