function sigma_ank = sigma_ank(in1,th)
%SIGMA_ANK
%    SIGMA_ANK = SIGMA_ANK(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-May-2020 22:28:44

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
t2 = q1+q2;
t3 = q3+q4+t2;
sigma_ank = tanh(th.*-4.0e+2+sin(q5+t3).*1.72e+2+sin(q1).*1.72e+2+sin(t2).*1.6e+2+sin(t3).*1.6e+2).*(-1.0./2.0)+1.0./2.0;
