function sigma = sigma_out(q1,q2,q3,q4,q5,q6,th)
%SIGMA_OUT
%    SIGMA = SIGMA_OUT(Q1,Q2,Q3,Q4,Q5,Q6,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    30-Apr-2020 17:29:30

t2 = q1+q2;
t3 = q3+q4+t2;
t4 = q5+t3;
sigma = tanh(th.*-4.0e+2+sin(q6+t4).*1.04e+2+sin(q1).*1.72e+2+sin(t2).*1.6e+2+sin(t3).*1.6e+2+sin(t4).*1.72e+2).*(-2.0./5.0)+2.0./5.0;
