function out1 = six_J_hip(q1,q2,q3,q4,q5,q6)
%SIX_J_HIP
%    OUT1 = SIX_J_HIP(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    16-Jun-2020 18:35:43

t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t3.*4.38012e-1;
t6 = t4.*4.38012e-1;
t7 = -t6;
out1 = reshape([t7-sin(q1).*4.5252e-1,t5+cos(q1).*4.5252e-1,0.0,0.0,0.0,1.0,t7,t5,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
