function out1 = six_J2(q1,q2,q3,q4,q5,q6)
%SIX_J2
%    OUT1 = SIX_J2(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    22-Jun-2020 12:50:38

t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = q3+q4+t2;
t6 = cos(t5);
t7 = q5+t5;
t8 = sin(t5);
t21 = t3.*4.38012e-1;
t22 = t4.*4.38012e-1;
t9 = q6+t7;
t10 = sin(t7);
t11 = cos(t7);
t23 = -t22;
t24 = t6.*4.38012e-1;
t25 = t8.*4.38012e-1;
t12 = cos(t9);
t13 = sin(t9);
t14 = t11.*4.5252e-1;
t15 = t10.*4.5252e-1;
t26 = -t25;
t16 = -t15;
t17 = t12.*4.5252e-1;
t18 = t13.*4.5252e-1;
t19 = -t17;
t20 = -t18;
t27 = t14+t20+t24;
t28 = t16+t19+t26;
out1 = reshape([t23+t28-sin(q1).*4.5252e-1,t21+t27+cos(q1).*4.5252e-1,0.0,0.0,0.0,1.0,t23+t28,t21+t27,0.0,0.0,0.0,1.0,t28,t27,0.0,0.0,0.0,1.0,t28,t27,0.0,0.0,0.0,1.0,t16+t19,t14+t20,0.0,0.0,0.0,1.0,t19,t20,0.0,0.0,0.0,1.0],[6,6]);
