function Crow = coriolis_row_2(rob,in2,in3)
%% CORIOLIS_ROW_2 - Computation of the robot specific Coriolis matrix row for joint 2 of 5. 
% ========================================================================= 
%    
%    Crow = coriolis_row_2(rob,q,qd) 
%    Crow = rob.coriolis_row_2(q,qd) 
%    
%  Description:: 
%    Given a full set of joint variables and their first order temporal derivatives this function computes the 
%    Coriolis matrix row number 2 of 5 for noname. 
%    
%  Input:: 
%    rob: robot object of noname specific class 
%    qd:  5-element vector of generalized 
%    q:  5-element vector of generalized 
%    
%  Output:: 
%    Crow:  [1x5] row of the robot Coriolis matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function. 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also coriolis.
%    
    
% Copyright (C) 1993-2020, by Peter I. Corke 
% Copyright (C) 2012-2020, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Apr-2020 23:52:36

q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
qd1 = in3(:,1);
qd2 = in3(:,2);
qd3 = in3(:,3);
qd4 = in3(:,4);
qd5 = in3(:,5);
t2 = sin(q3);
t3 = sin(q5);
t4 = q3+q4;
t5 = q5+t4;
t6 = sin(t4);
t8 = qd5.*t3.*3.4732e-1;
t10 = qd3.*t2.*4.72468;
t7 = sin(t5);
t9 = -t8;
t11 = qd1.*t6.*1.25956;
t12 = qd2.*t6.*1.25956;
t13 = qd3.*t6.*1.25956;
t14 = qd4.*t6.*1.25956;
t15 = -t10;
t16 = -t11;
t17 = -t12;
t18 = -t13;
t19 = -t14;
t20 = qd1.*t7.*3.4732e-1;
t21 = qd2.*t7.*3.4732e-1;
t22 = qd3.*t7.*3.4732e-1;
t23 = qd4.*t7.*3.4732e-1;
t24 = qd5.*t7.*3.4732e-1;
t25 = -t20;
t26 = -t21;
t27 = -t22;
t28 = -t23;
t29 = -t24;
Crow = [t9+t15+t18+t19+t27+t28+t29+qd1.*sin(q2+q3).*5.079031+qd1.*sin(q2+t4).*1.354027+qd1.*sin(q2+t5).*3.73369e-1+qd1.*sin(q2).*9.896493,t9+t15+t18+t19+t27+t28+t29,t9+t15+t16+t17+t18+t19+t25+t26+t27+t28+t29-qd1.*t2.*4.72468-qd2.*t2.*4.72468,t9+t16+t17+t18+t19+t25+t26+t27+t28+t29,(t3+t7).*(qd1+qd2+qd3+qd4+qd5).*(-3.4732e-1)];
