function Crow = coriolis_row_1(rob,in2,in3)
%% CORIOLIS_ROW_1 - Computation of the robot specific Coriolis matrix row for joint 1 of 5. 
% ========================================================================= 
%    
%    Crow = coriolis_row_1(rob,q,qd) 
%    Crow = rob.coriolis_row_1(q,qd) 
%    
%  Description:: 
%    Given a full set of joint variables and their first order temporal derivatives this function computes the 
%    Coriolis matrix row number 1 of 5 for noname. 
%    
%  Input:: 
%    rob: robot object of noname specific class 
%    qd:  5-element vector of generalized 
%    q:  5-element vector of generalized 
%    
%  Output:: 
%    Crow:  [1x5] row of the robot Coriolis matrix 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function. 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also coriolis.
%    
    
% Copyright (C) 1993-2020, by Peter I. Corke 
% Copyright (C) 2012-2020, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    23-Apr-2020 23:52:36

q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
q5 = in2(:,5);
qd1 = in3(:,1);
qd2 = in3(:,2);
qd3 = in3(:,3);
qd4 = in3(:,4);
qd5 = in3(:,5);
t2 = sin(q2);
t3 = sin(q3);
t4 = sin(q5);
t5 = q2+q3;
t6 = q3+q4;
t7 = q4+t5;
t8 = q5+t6;
t9 = sin(t5);
t10 = sin(t6);
t15 = qd5.*t4.*3.4732e-1;
t17 = qd3.*t3.*4.72468;
t37 = qd2.*t2.*9.896493;
t11 = q5+t7;
t12 = sin(t7);
t13 = sin(t8);
t16 = -t15;
t18 = qd1.*t10.*1.25956;
t19 = qd2.*t10.*1.25956;
t20 = qd3.*t10.*1.25956;
t21 = qd4.*t10.*1.25956;
t22 = -t17;
t38 = qd1.*t9.*5.079031;
t39 = qd2.*t9.*5.079031;
t40 = qd3.*t9.*5.079031;
t41 = -t37;
t14 = sin(t11);
t23 = -t18;
t24 = -t19;
t25 = -t20;
t26 = -t21;
t27 = qd1.*t13.*3.4732e-1;
t28 = qd2.*t13.*3.4732e-1;
t29 = qd3.*t13.*3.4732e-1;
t30 = qd4.*t13.*3.4732e-1;
t31 = qd5.*t13.*3.4732e-1;
t47 = -t38;
t48 = -t39;
t49 = -t40;
t50 = qd1.*t12.*1.354027;
t51 = qd2.*t12.*1.354027;
t52 = qd3.*t12.*1.354027;
t53 = qd4.*t12.*1.354027;
t32 = -t27;
t33 = -t28;
t34 = -t29;
t35 = -t30;
t36 = -t31;
t42 = qd1.*t14.*3.73369e-1;
t43 = qd2.*t14.*3.73369e-1;
t44 = qd3.*t14.*3.73369e-1;
t45 = qd4.*t14.*3.73369e-1;
t46 = qd5.*t14.*3.73369e-1;
t59 = -t50;
t60 = -t51;
t61 = -t52;
t62 = -t53;
t54 = -t42;
t55 = -t43;
t56 = -t44;
t57 = -t45;
t58 = -t46;
Crow = [t16+t22+t25+t26+t34+t35+t36+t41+t48+t49+t55+t56+t57+t58+t60+t61+t62,t16+t22+t25+t26+t34+t35+t36+t41+t47+t48+t49+t54+t55+t56+t57+t58+t59+t60+t61+t62-qd1.*t2.*9.896493,t16+t22+t23+t24+t25+t26+t32+t33+t34+t35+t36+t47+t48+t49+t54+t55+t56+t57+t58+t59+t60+t61+t62-qd1.*t3.*4.72468-qd2.*t3.*4.72468,t16+t23+t24+t25+t26+t32+t33+t34+t35+t36+t54+t55+t56+t57+t58+t59+t60+t61+t62,(t4.*4.0e+1+t13.*4.0e+1+t14.*4.3e+1).*(qd1+qd2+qd3+qd4+qd5).*(-8.683e-3)];
