function out1 = six_J2(q1,q2,q3,q4,q5,q6)
%SIX_J2
%    OUT1 = SIX_J2(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    27-May-2020 00:59:59

t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = q3+q4+t2;
t6 = cos(t5);
t7 = q5+t5;
t8 = sin(t5);
t14 = t3.*4.38012e-1;
t15 = t4.*4.38012e-1;
t9 = sin(t7);
t10 = cos(t7);
t16 = -t15;
t17 = t6.*4.38012e-1;
t18 = t8.*4.38012e-1;
t11 = t10.*5.2902e-1;
t12 = t9.*5.2902e-1;
t19 = -t18;
t13 = -t12;
t20 = t11+t17;
t21 = t13+t19;
out1 = reshape([t16+t21-sin(q1).*4.5252e-1,t14+t20+cos(q1).*4.5252e-1,0.0,0.0,0.0,1.0,t16+t21,t14+t20,0.0,0.0,0.0,1.0,t21,t20,0.0,0.0,0.0,1.0,t21,t20,0.0,0.0,0.0,1.0,t13,t11,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
