function dHip_vel_q1 = dHip_vel_q1(in1,in2,sampT)
%DHIP_VEL_Q1
%    DHIP_VEL_Q1 = DHIP_VEL_Q1(IN1,IN2,SAMPT)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    25-Jul-2020 23:17:37

q_t1 = in1(:,1);
q_t2 = in1(:,2);
qd_t1 = in2(:,1);
qd_t2 = in2(:,2);
t2 = cos(q_t1);
t3 = sin(q_t1);
t4 = q_t1+q_t2;
t7 = 1.0./sampT;
t5 = cos(t4);
t6 = sin(t4);
t8 = t2.*4.60062e-1;
t9 = t3.*4.60062e-1;
t10 = t5.*4.453122e-1;
t11 = t6.*4.453122e-1;
t12 = qd_t2.*t5.*2.226561e-1;
t13 = qd_t2.*t6.*2.226561e-1;
t14 = -t12;
t15 = -t13;
t16 = t8+t10;
t17 = t9+t11;
dHip_vel_q1 = [t14-(qd_t1.*t16)./2.0+t7.*t17;t15-(qd_t1.*t17)./2.0-t7.*t16;0.0;t14-qd_t1.*t5.*2.226561e-1+t7.*t11;t15-qd_t1.*t6.*2.226561e-1-t5.*t7.*4.453122e-1;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0;0.0];
