function end_x_grad = end_x_grad(q1,q2,q3,q4,q5)
%END_X_GRAD
%    END_X_GRAD = END_X_GRAD(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    24-Apr-2020 12:32:12

t2 = q1+q2;
t3 = sin(t2);
t4 = q3+q4+t2;
t5 = q5+t4;
t6 = sin(t4);
t8 = t3.*(2.0./5.0);
t7 = sin(t5);
t9 = -t8;
t10 = t6.*(2.0./5.0);
t11 = -t10;
t12 = t7.*(4.3e+1./1.0e+2);
t13 = -t12;
t14 = t11+t13;
end_x_grad = [t9+t14-sin(q1).*(4.3e+1./1.0e+2),t9+t14,t14,t14,t13];
