function dGrf_c2F = dGrf_c2_F(in1,us)
%DGRF_C2_F
%    DGRF_C2F = DGRF_C2_F(IN1,US)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    25-Jul-2020 23:25:26

Fx = in1(:,1);
Fy = in1(:,2);
dGrf_c2F = [Fx.*2.0;Fy.*us.^2.*-2.0];
