function out1 = head_y_pos(in1)
%HEAD_Y_POS
%    OUT1 = HEAD_Y_POS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    21-Apr-2020 22:42:55

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
t2 = q1+q2;
out1 = sin(q3+t2).*(9.0./1.0e+1)+sin(q1).*(9.0./2.0e+1)+sin(t2).*(9.0./2.0e+1);
