function Grf_toe_c4 = Grf_toe_c4(in1,in2,Fx)
%GRF_TOE_C4
%    GRF_TOE_C4 = GRF_TOE_C4(IN1,IN2,FX)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    26-Jul-2020 23:28:52

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
qd_t1 = in2(:,1);
qd_t2 = in2(:,2);
qd_t3 = in2(:,3);
qd_t4 = in2(:,4);
qd_t5 = in2(:,5);
qd_t6 = in2(:,6);
t2 = q_t1+q_t2;
t9 = atan(1.929566117647059);
t10 = 1.903089174117337e+18;
t3 = sin(t2);
t4 = q_t3+q_t4+t2;
t13 = -t9;
t5 = q_t5+t4;
t6 = sin(t4);
t8 = t3.*4.453122e-1;
t7 = sin(t5);
t11 = t6.*4.453122e-1;
t14 = q_t6+t5+t13;
t12 = t7.*4.60062e-1;
t15 = cos(t14);
t16 = (t10.*t15)./1.125899906842624e+19;
t17 = t11+t12+t16;
Grf_toe_c4 = -Fx.*(qd_t2.*(t8+t17)+qd_t5.*(t12+t16)+qd_t1.*(t8+t17+sin(q_t1).*4.60062e-1)+qd_t3.*t17+qd_t4.*t17+qd_t6.*t16);
