function end_y_pos = end_y_pos(in1)
%END_Y_POS
%    END_Y_POS = END_Y_POS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-May-2020 14:55:24

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2;
t3 = q3+q4+t2;
t4 = q5+t3;
end_y_pos = sin(q1).*4.446e-1+sin(t2).*(2.61e+2./6.25e+2)+sin(t3).*(2.61e+2./6.25e+2)+sin(t4).*4.446e-1+2.432562589705372e+17.*cos(q6+t4-atan(3.488235294117647e-1)).*3.33066907387547e-19;
