function end_y_grad = end_y_grad(in1)
%END_Y_GRAD
%    END_Y_GRAD = END_Y_GRAD(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-May-2020 14:55:24

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2;
t11 = atan(3.488235294117647e-1);
t12 = 2.432562589705372e+17;
t3 = cos(t2);
t4 = q3+q4+t2;
t13 = -t11;
t5 = cos(t4);
t6 = q5+t4;
t8 = t3.*(2.61e+2./6.25e+2);
t7 = cos(t6);
t9 = t5.*(2.61e+2./6.25e+2);
t14 = q6+t6+t13;
t10 = t7.*4.446e-1;
t15 = sin(t14);
t16 = t12.*t15.*3.33066907387547e-19;
t17 = -t16;
t18 = t9+t10+t17;
end_y_grad = [t8+t18+cos(q1).*4.446e-1,t8+t18,t18,t18,t10+t17,t17];
