function end_x_grad = end_x_grad(q1,q2,q3,q4,q5,q6)
%END_X_GRAD
%    END_X_GRAD = END_X_GRAD(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-May-2020 14:55:24

t2 = q1+q2;
t14 = atan(2.866779089376054);
t15 = 2.432562589705372e+17;
t3 = sin(t2);
t4 = q3+q4+t2;
t5 = q5+t4;
t6 = sin(t4);
t8 = t3.*(2.61e+2./6.25e+2);
t7 = sin(t5);
t9 = -t8;
t10 = t6.*(2.61e+2./6.25e+2);
t16 = q6+t5+t14;
t11 = -t10;
t12 = t7.*4.446e-1;
t17 = sin(t16);
t13 = -t12;
t18 = t15.*t17.*3.33066907387547e-19;
t19 = -t18;
t20 = t11+t13+t19;
end_x_grad = [t9+t20-sin(q1).*4.446e-1,t9+t20,t20,t20,t13+t19,t19];
