function end_x_pos = end_x_pos(q1,q2,q3,q4,q5,q6)
%END_X_POS
%    END_X_POS = END_X_POS(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-May-2020 14:55:24

t2 = q1+q2;
t3 = q3+q4+t2;
t4 = q5+t3;
end_x_pos = cos(q1).*4.446e-1+cos(t2).*(2.61e+2./6.25e+2)+cos(t3).*(2.61e+2./6.25e+2)+cos(t4).*4.446e-1+2.432562589705372e+17.*cos(q6+t4+atan(2.866779089376054)).*3.33066907387547e-19;
