function head_y_pos = head_y_pos(in1)
%HEAD_Y_POS
%    HEAD_Y_POS = HEAD_Y_POS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-May-2020 14:55:29

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
t2 = q1+q2;
head_y_pos = sin(q3+t2).*7.335e-1+sin(q1).*4.446e-1+sin(t2).*(2.61e+2./6.25e+2);
