function heel_y_grad = heel_y_grad(in1)
%HEEL_Y_GRAD
%    HEEL_Y_GRAD = HEEL_Y_GRAD(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-May-2020 14:55:29

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q3);
t10 = sin(q4);
t11 = sin(q5);
t12 = t2.*t3;
t13 = t2.*t8;
t14 = t3.*t7;
t15 = t7.*t8;
t16 = -t15;
t17 = t13+t14;
t18 = t12.*(2.61e+2./6.25e+2);
t19 = t15.*(2.61e+2./6.25e+2);
t20 = t12+t16;
t21 = -t19;
t22 = t4.*t17;
t23 = t9.*t17;
t24 = t4.*t20;
t25 = t9.*t20;
t26 = -t23;
t27 = t22+t25;
t28 = t24+t26;
t31 = -t5.*(t23-t24);
t32 = -t10.*(t23-t24);
t36 = t5.*(t23-t24).*(-2.61e+2./6.25e+2);
t29 = t5.*t27;
t30 = t10.*t27;
t33 = -t30;
t34 = t30.*(2.61e+2./6.25e+2);
t37 = t29+t32;
t41 = t6.*(t30+t5.*(t23-t24)).*(-5.211e-1);
t35 = -t34;
t38 = t31+t33;
t39 = t11.*t37.*5.211e-1;
t40 = -t39;
t42 = t35+t36+t40+t41;
heel_y_grad = [t2.*4.446e-1+t18+t21+t42,t18+t21+t42,t42,t42,t40+t41,0.0];
