function hip_x_pos = hip_x_pos(in1)
%HIP_X_POS
%    HIP_X_POS = HIP_X_POS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    10-Jun-2020 15:00:20

q1 = in1(:,1);
q2 = in1(:,2);
hip_x_pos = cos(q1+q2).*4.38012e-1+cos(q1).*4.5252e-1;
