function hip_x_pos = hip_x_pos(in1)
%HIP_X_POS
%    HIP_X_POS = HIP_X_POS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    19-May-2020 14:55:29

q1 = in1(:,1);
q2 = in1(:,2);
hip_x_pos = cos(q1+q2).*(2.61e+2./6.25e+2)+cos(q1).*4.446e-1;
