function end_y_grad = end_y_grad(in1)
%END_Y_GRAD
%    END_Y_GRAD = END_Y_GRAD(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-May-2020 16:05:47

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2;
t5 = atan(7.0./2.6e+1);
t6 = sqrt(2.9e+1);
t3 = cos(t2);
t4 = q3+q4+t2;
t7 = cos(t4);
t8 = q5+t4;
t10 = t3.*(2.0./5.0);
t9 = cos(t8);
t11 = t7.*(2.0./5.0);
t12 = q6+t5+t8;
t13 = cos(t12);
t14 = t9.*(4.3e+1./1.0e+2);
t15 = (t6.*t13)./2.0e+1;
t16 = t11+t14+t15;
end_y_grad = [t10+t16+cos(q1).*(4.3e+1./1.0e+2),t10+t16,t16,t16,t14+t15,t15];
