function end_y_grad = end_y_grad(in1)
%END_Y_GRAD
%    END_Y_GRAD = END_Y_GRAD(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    10-May-2020 17:11:25

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+q4+t2;
t5 = cos(t4);
t6 = q5+t4;
t9 = t3.*(2.0./5.0);
t7 = q6+t6;
t8 = cos(t6);
t11 = t5.*(2.0./5.0);
t10 = cos(t7);
t12 = t8.*(4.3e+1./1.0e+2);
t13 = t10.*(1.3e+1./5.0e+1);
t14 = t11+t12+t13;
end_y_grad = [t9+t14+cos(q1).*(4.3e+1./1.0e+2),t9+t14,t14,t14,t12+t13,t13];
