function end_x_grad = end_x_grad(q1,q2,q3,q4,q5,q6)
%END_X_GRAD
%    END_X_GRAD = END_X_GRAD(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-May-2020 16:05:47

t2 = q1+q2;
t5 = atan(7.0./2.6e+1);
t6 = sqrt(2.9e+1);
t3 = sin(t2);
t4 = q3+q4+t2;
t7 = q5+t4;
t8 = sin(t4);
t10 = t3.*(2.0./5.0);
t9 = sin(t7);
t11 = -t10;
t12 = t8.*(2.0./5.0);
t14 = q6+t5+t7;
t13 = -t12;
t15 = sin(t14);
t16 = t9.*(4.3e+1./1.0e+2);
t17 = -t16;
t18 = (t6.*t15)./2.0e+1;
t19 = -t18;
t20 = t13+t17+t19;
end_x_grad = [t11+t20-sin(q1).*(4.3e+1./1.0e+2),t11+t20,t20,t20,t17+t19,t19];
