function heel_x_grad = heel_x_grad(in1)
%HEEL_X_GRAD
%    HEEL_X_GRAD = HEEL_X_GRAD(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-May-2020 16:05:51

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q3);
t10 = sin(q4);
t11 = sin(q5);
t12 = t2.*t3;
t13 = t2.*t8;
t14 = t3.*t7;
t15 = t7.*t8;
t16 = -t15;
t17 = t13.*(2.0./5.0);
t18 = t14.*(2.0./5.0);
t21 = t13+t14;
t19 = -t17;
t20 = -t18;
t22 = t12+t16;
t23 = t4.*t21;
t24 = t9.*t21;
t25 = t4.*t22;
t26 = t9.*t22;
t27 = -t24;
t28 = t23+t26;
t29 = t25+t27;
t32 = -t5.*(t24-t25);
t33 = -t10.*(t24-t25);
t37 = t10.*(t24-t25).*(-2.0./5.0);
t38 = t10.*(t24-t25).*(2.0./5.0);
t30 = t5.*t28;
t31 = t10.*t28;
t34 = -t31;
t35 = t30.*(2.0./5.0);
t39 = t30+t33;
t43 = t11.*(t31+t5.*(t24-t25)).*(-1.0./2.0);
t44 = (t11.*(t31+t5.*(t24-t25)))./2.0;
t36 = -t35;
t40 = t32+t34;
t41 = (t6.*t39)./2.0;
t42 = -t41;
t45 = t36+t38+t42+t44;
heel_x_grad = [t7.*(-4.3e+1./1.0e+2)+t19+t20+t45,t19+t20+t45,t45,t45,t42+t44,0.0];
