function hip_x_pos = hip_x_pos(in1)
%HIP_X_POS
%    HIP_X_POS = HIP_X_POS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-May-2020 16:05:54

q1 = in1(:,1);
q2 = in1(:,2);
hip_x_pos = cos(q1+q2).*(2.0./5.0)+cos(q1).*(4.3e+1./1.0e+2);
