function dM_dx5 = dM_dx5(q2,q3,q4,q5,q6)
%DM_DX5
%    DM_DX5 = DM_DX5(Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-May-2020 16:40:58

t2 = sin(q5);
t3 = q5+q6;
t4 = q3+q4+q5;
t5 = sin(t3);
t6 = q2+t4;
t7 = q3+q4+t3;
t8 = sin(t4);
t17 = t2.*8.9624e-1;
t18 = t2.*4.4812e-1;
t9 = q2+t7;
t10 = sin(t6);
t11 = sin(t7);
t13 = t5.*1.092e-1;
t14 = t5.*5.46e-2;
t19 = -t17;
t20 = -t18;
t25 = t8.*8.9624e-1;
t26 = t8.*4.4812e-1;
t12 = sin(t9);
t15 = -t13;
t16 = -t14;
t21 = t11.*1.092e-1;
t22 = t11.*5.46e-2;
t27 = -t25;
t28 = -t26;
t31 = t10.*4.81729e-1;
t23 = -t21;
t24 = -t22;
t29 = t12.*5.8695e-2;
t32 = -t31;
t33 = t15+t19;
t34 = t16+t20;
t30 = -t29;
t35 = t16+t24;
t37 = t24+t28+t33;
t38 = t24+t28+t34;
t36 = t30+t35;
t39 = t23+t27+t30+t32+t33;
t40 = t30+t32+t37;
t41 = t30+t32+t38;
dM_dx5 = reshape([t10.*(-9.63458e-1)-t12.*1.1739e-1+t23+t27+t33,t39,t40,t40,t41,t36,t39,t23+t27+t33,t37,t37,t38,t35,t40,t37,t33,t33,t34,t16,t40,t37,t33,t33,t34,t16,t41,t38,t34,t34,0.0,0.0,t36,t35,t16,t16,0.0,0.0],[6,6]);
