function dM_dx6 = dM_dx6(q2,q3,q4,q5,q6)
%DM_DX6
%    DM_DX6 = DM_DX6(Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-May-2020 16:40:58

t2 = sin(q6);
t3 = q5+q6;
t4 = sin(t3);
t5 = q3+q4+t3;
t13 = t2.*1.1739e-1;
t14 = t2.*5.8695e-2;
t6 = q2+t5;
t7 = sin(t5);
t9 = t4.*1.092e-1;
t10 = t4.*5.46e-2;
t17 = -t13;
t18 = -t14;
t8 = sin(t6);
t11 = -t9;
t12 = -t10;
t15 = t7.*1.092e-1;
t16 = t7.*5.46e-2;
t19 = -t15;
t20 = -t16;
t21 = t8.*5.8695e-2;
t23 = t11+t17;
t24 = t12+t17;
t25 = t12+t18;
t22 = -t21;
t26 = t20+t23;
t27 = t20+t24;
t28 = t20+t25;
t29 = t19+t22+t23;
t30 = t22+t26;
t31 = t22+t27;
t32 = t22+t28;
dM_dx6 = reshape([t8.*(-1.1739e-1)+t19+t23,t29,t30,t30,t31,t32,t29,t19+t23,t26,t26,t27,t28,t30,t26,t23,t23,t24,t25,t30,t26,t23,t23,t24,t25,t31,t27,t24,t24,t17,t18,t32,t28,t25,t25,t18,0.0],[6,6]);
