function ypos = end_y_pos(q)
%END_Y_POS
%    YPOS = END_Y_POS(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    11-Apr-2020 15:27:51


%% 
% in order to apply parallel toolbox, the input x is the whole dataset, and
% idx is the array we use in iteration


q1 = q(1);
q2 = q(2);
q3 = q(3);
q4 = q(4);
q5 = q(5);
t2 = q1+q2;
t3 = q3+q4+t2;
ypos = sin(q5+t3).*(9.0./2.0e+1)+sin(q1).*(9.0./2.0e+1)+sin(t2).*(9.0./2.0e+1)+sin(t3).*(9.0./2.0e+1);
