function ypos_grad = end_y_poss_grad(x)
%END_Y_POSS_GRAD
%    YPOS_GRAD = END_Y_POSS_GRAD(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Apr-2020 12:28:36
q1 =x(1);
q2=x(2);
q3=x(3);
q4=x(4);
q5=x(5);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+q4+t2;
t5 = cos(t4);
t6 = q5+t4;
t8 = t3.*(9.0./2.0e+1);
t7 = cos(t6);
t9 = t5.*(9.0./2.0e+1);
t10 = t7.*(9.0./2.0e+1);
t11 = t9+t10;
ypos_grad = [t8+t11+cos(q1).*(9.0./2.0e+1),t8+t11,t11,t11,t10];
