function ypos = end_y_pos(x)
%END_Y_POS
%    YPOS = END_Y_POS(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Apr-2020 12:28:35
q1=x(1);
q2=x(2);
q3=x(3);
q4=x(4);
q5=x(5);
t2 = q1+q2;
t3 = q3+q4+t2;
ypos = sin(q5+t3).*(9.0./2.0e+1)+sin(q1).*(9.0./2.0e+1)+sin(t2).*(9.0./2.0e+1)+sin(t3).*(9.0./2.0e+1);
