function xpos = end_x_pos(q1,q2,q3,q4,q5)
%END_X_POS
%    XPOS = END_X_POS(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Apr-2020 01:28:46

t2 = q1+q2;
t3 = q3+q4+t2;
xpos = cos(q5+t3).*(9.0./2.0e+1)+cos(q1).*(9.0./2.0e+1)+cos(t2).*(9.0./2.0e+1)+cos(t3).*(9.0./2.0e+1);
