function endPos = endPos(q1,q2,q3,q4,q5)
%ENDPOS
%    ENDPOS = ENDPOS(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    03-Apr-2020 23:50:11

t2 = q1+q2;
t3 = q3+q4+t2;
t4 = q5+t3;
endPos = [cos(q1).*(9.0./2.0e+1)+cos(t2).*(9.0./2.0e+1)+cos(t3).*(9.0./2.0e+1)+cos(t4).*(9.0./2.0e+1);sin(q1).*(9.0./2.0e+1)+sin(t2).*(9.0./2.0e+1)+sin(t3).*(9.0./2.0e+1)+sin(t4).*(9.0./2.0e+1);0.0];
