function out1 = five_link_head_h(x)
%FIVE_LINK_HEAD_H
%    OUT1 = FIVE_LINK_HEAD_H(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Apr-2020 01:33:56
q1=x(1);
q2=x(2);
q3=x(3);
t2 = q1+q2;
out1 = sin(q3+t2).*(9.0./1.0e+1)+sin(q1).*(9.0./2.0e+1)+sin(t2).*(9.0./2.0e+1);
