function head_h_grad = five_link_head_grad(x)
%FIVE_LINK_HEAD_GRAD
%    HEAD_H_GRAD = FIVE_LINK_HEAD_GRAD(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Apr-2020 01:33:56
q1=x(1);
q2=x(2);
q3=x(3);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+t2;
t5 = cos(t4);
t6 = t3.*(9.0./2.0e+1);
t7 = t5.*(9.0./1.0e+1);
head_h_grad = [t6+t7+cos(q1).*(9.0./2.0e+1),t6+t7,0.0];
