function J_toe = J_toe(in1)
%J_TOE
%    J_TOE = J_TOE(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    25-Jul-2020 23:15:55

q_t1 = in1(:,1);
q_t2 = in1(:,2);
q_t3 = in1(:,3);
q_t4 = in1(:,4);
q_t5 = in1(:,5);
q_t6 = in1(:,6);
t2 = q_t1+q_t2;
t11 = atan(4.031084689959317e-1);
t12 = atan(2.480721882352941);
t13 = 1.951787129631e+17;
t3 = cos(t2);
t4 = sin(t2);
t5 = q_t3+q_t4+t2;
t17 = -t12;
t6 = cos(t5);
t7 = q_t5+t5;
t8 = sin(t5);
t14 = t3.*4.453122e-1;
t15 = t4.*4.453122e-1;
t9 = sin(t7);
t10 = cos(t7);
t16 = -t15;
t18 = t6.*4.453122e-1;
t19 = t8.*4.453122e-1;
t24 = q_t6+t7+t11;
t26 = q_t6+t7+t17;
t20 = t10.*4.60062e-1;
t21 = t9.*4.60062e-1;
t22 = -t19;
t25 = cos(t24);
t27 = cos(t26);
t23 = -t21;
t28 = t13.*t25.*1.06581410364015e-18;
t29 = t13.*t27.*1.06581410364015e-18;
t30 = -t29;
t31 = t18+t20+t28;
t32 = t22+t23+t30;
J_toe = reshape([t16+t32-sin(q_t1).*4.60062e-1,t14+t31+cos(q_t1).*4.60062e-1,0.0,t16+t32,t14+t31,0.0,t32,t31,0.0,t32,t31,0.0,t23+t30,t20+t28,0.0,t30,t28,0.0],[3,6]);
