function endPos = five_link_endPos(q1,q2,q3,q4,q5)
%FIVE_LINK_ENDPOS
%    ENDPOS = FIVE_LINK_ENDPOS(Q1,Q2,Q3,Q4,Q5)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Apr-2020 01:05:23

t2 = q1+q2;
t3 = q3+q4+t2;
t4 = q5+t3;
endPos = [cos(q1).*(9.0./2.0e+1)+cos(t2).*(9.0./2.0e+1)+cos(t3).*(9.0./2.0e+1)+cos(t4).*3.048e-1;sin(q1).*(9.0./2.0e+1)+sin(t2).*(9.0./2.0e+1)+sin(t3).*(9.0./2.0e+1)+sin(t4).*3.048e-1;0.0];
