function headPos = five_link_headPos(q1,q2,q3)
%FIVE_LINK_HEADPOS
%    HEADPOS = FIVE_LINK_HEADPOS(Q1,Q2,Q3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    20-Apr-2020 01:05:23

t2 = q1+q2;
t3 = q3+t2;
headPos = [cos(q1).*(9.0./2.0e+1)+cos(t2).*(9.0./2.0e+1)+cos(t3).*(9.0./1.0e+1);sin(q1).*(9.0./2.0e+1)+sin(t2).*(9.0./2.0e+1)+sin(t3).*(9.0./1.0e+1);0.0];
