function sigma = sigma_out(q1,q2,q3,q4,q5,th)
%SIGMA_OUT
%    SIGMA = SIGMA_OUT(Q1,Q2,Q3,Q4,Q5,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    14-Apr-2020 16:02:05

t2 = q1+q2;
t3 = q3+q4+t2;
sigma = tanh(-th+sin(q5+t3).*(9.0./2.0e+1)+sin(q1).*(9.0./2.0e+1)+sin(t2).*(9.0./2.0e+1)+sin(t3).*(9.0./2.0e+1))./2.0;
