function dHip_x_vel = dHip_x_vel(in1)
%DHIP_X_VEL
%    DHIP_X_VEL = DHIP_X_VEL(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    16-Jun-2020 20:49:44

q1 = in1(:,1);
q2 = in1(:,2);
qd1 = in1(:,7);
qd2 = in1(:,8);
t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = t4.*4.38012e-1;
t7 = qd2.*t3.*4.38012e-1;
t6 = -t5;
t8 = -t7;
dHip_x_vel = [t8-qd1.*(t3.*4.38012e-1+cos(q1).*4.5252e-1);t8-qd1.*t3.*4.38012e-1;0.0;0.0;0.0;0.0;t6-sin(q1).*4.5252e-1;t6;0.0;0.0;0.0;0.0];
