function end_x_grad = end_x_grad(q1,q2,q3,q4,q5,q6)
%END_X_GRAD
%    END_X_GRAD = END_X_GRAD(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    24-Jun-2020 02:27:09

t2 = q1+q2;
t8 = atan(2.87940379403794e-1);
t9 = 1.535969075209524e+3;
t3 = sin(t2);
t4 = q3+q4+t2;
t5 = q5+t4;
t6 = sin(t4);
t16 = t3.*4.38012e-1;
t7 = sin(t5);
t10 = q6+t5+t8;
t17 = -t16;
t18 = t6.*4.38012e-1;
t11 = sin(t10);
t12 = t7.*4.5252e-1;
t19 = -t18;
t13 = -t12;
t14 = t9.*t11.*1.8e-4;
t15 = -t14;
t20 = t13+t15+t19;
end_x_grad = [t17+t20-sin(q1).*4.5252e-1,t17+t20,t20,t20,t13+t15,t15];
