function heel_x_pos = heel_x_pos(in1)
%HEEL_X_POS
%    HEEL_X_POS = HEEL_X_POS(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    22-Jun-2020 12:47:19

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q3);
t10 = sin(q4);
t11 = sin(q5);
t12 = t2.*t3;
t13 = t2.*t8;
t14 = t3.*t7;
t15 = t7.*t8;
t16 = -t15;
t17 = t13+t14;
t18 = t12+t16;
t19 = t4.*t17;
t20 = t9.*t17;
t21 = t4.*t18;
t22 = t9.*t18;
t23 = -t20;
t24 = t19+t22;
t25 = t21+t23;
t28 = -t5.*(t20-t21);
t29 = -t10.*(t20-t21);
t26 = t5.*t24;
t27 = t10.*t24;
t30 = -t27;
t31 = t26+t29;
t32 = t28+t30;
heel_x_pos = t2.*4.5252e-1+t12.*4.38012e-1-t15.*4.38012e-1-t27.*4.38012e-1+sin(q6).*(t6.*(t27+t5.*(t20-t21))+t11.*t31).*7.65e-2-t6.*(t27+t5.*(t20-t21)).*4.5252e-1-t11.*t31.*4.5252e-1-t5.*(t20-t21).*4.38012e-1+cos(q6).*(t11.*(t27+t5.*(t20-t21))-t6.*t31).*7.65e-2;
