function hip_x_grad = hip_x_grad(in1)
%HIP_X_GRAD
%    HIP_X_GRAD = HIP_X_GRAD(IN1)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    22-Jun-2020 12:47:53

q1 = in1(:,1);
q2 = in1(:,2);
t2 = q1+q2;
t3 = sin(t2);
t4 = t3.*4.38012e-1;
t5 = -t4;
hip_x_grad = [t5-sin(q1).*4.5252e-1,t5,0.0];
