function Iacc = Iqdd(rob,in2,in3,in4)
%% IQDD - Vector of computed inertial forces/torques for noname 
% ========================================================================= 
%    
%    Iacc = Iqdd(rob,q,qd,tau) 
%    Iacc = rob.Iqdd(q,qd,tau) 
%    
%  Description:: 
%    Given a full set of joint variables, their temporal derivatives and applied joint forces/torques 
%    this function computes the reaction inertial forces/torques due to joint acceleration. 
%    
%  Input:: 
%    rob: robot object of noname specific class 
%    q:  4-element vector of generalized 
%         coordinates 
%    qd:  4-element vector of generalized 
%         velocities 
%    tau:  4-element vector of joint 
%         input forces/torques 
%    Angles have to be given in radians! 
%    
%  Output:: 
%    Iqdd:  [1x4] vector of inertial reaction forces/torques 
%    
%  Example:: 
%    --- 
%    
%  Known Bugs:: 
%    --- 
%    
%  TODO:: 
%    --- 
%    
%  References:: 
%    1) Robot Modeling and Control - Spong, Hutchinson, Vidyasagar 
%    2) Modelling and Control of Robot Manipulators - Sciavicco, Siciliano 
%    3) Introduction to Robotics, Mechanics and Control - Craig 
%    4) Modeling, Identification & Control of Robots - Khalil & Dombre 
%    
%  Authors:: 
%    This is an autogenerated function! 
%    Code generator written by: 
%    Joern Malzahn 
%    2012 RST, Technische Universitaet Dortmund, Germany 
%    http://www.rst.e-technik.tu-dortmund.de 
%    
%  See also accel.
%    
    
% Copyright (C) 1993-2020, by Peter I. Corke 
% Copyright (C) 2012-2020, by Joern Malzahn 
% 
% This file has been automatically generated with The Robotics Toolbox for Matlab (RTB). 
% 
% RTB and code generated with RTB is free software: you can redistribute it and/or modify 
% it under the terms of the GNU Lesser General Public License as published by 
% the Free Software Foundation, either version 3 of the License, or 
% (at your option) any later version. 
%  
% RTB is distributed in the hope that it will be useful, 
% but WITHOUT ANY WARRANTY; without even the implied warranty of 
% MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the 
% GNU Lesser General Public License for more details. 
%  
% You should have received a copy of the GNU Leser General Public License 
% along with RTB.  If not, see <http://www.gnu.org/licenses/>. 
% 
% http://www.petercorke.com 
% 
% The code generation module emerged during the work on a project funded by 
% the German Research Foundation (DFG, BE1569/7-1). The authors gratefully  
% acknowledge the financial support. 

%% Bugfix
%  In some versions the symbolic toolbox writes the constant $pi$ in
%  capital letters. This way autogenerated functions might not work properly.
%  To fix this issue a local variable is introduced:
PI = pi;
   




%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    01-Apr-2020 19:54:51

Q1 = in4(:,1);
Q2 = in4(:,2);
Q3 = in4(:,3);
Q4 = in4(:,4);
q2 = in2(:,2);
q3 = in2(:,3);
q4 = in2(:,4);
qd1 = in3(:,1);
qd2 = in3(:,2);
qd3 = in3(:,3);
qd4 = in3(:,4);
t2 = sin(q2);
t3 = sin(q3);
t4 = sin(q4);
t5 = q2+q3;
t6 = q3+q4;
t10 = qd1+qd2+qd3+qd4;
t7 = q4+t5;
t8 = sin(t5);
t9 = sin(t6);
t12 = qd1.*t4.*1.181061e+1;
t13 = qd2.*t4.*1.181061e+1;
t14 = qd3.*t4.*1.181061e+1;
t15 = qd4.*t4.*1.181061e+1;
t16 = qd1.*t3.*1.25547975e+1;
t17 = qd2.*t3.*1.25547975e+1;
t18 = qd3.*t3.*1.25547975e+1;
t24 = qd1.*t2.*9.23587434;
t25 = qd2.*t2.*9.23587434;
t11 = sin(t7);
t19 = -t15;
t20 = qd1.*t9.*1.181061e+1;
t21 = qd2.*t9.*1.181061e+1;
t22 = qd3.*t9.*1.181061e+1;
t23 = qd4.*t9.*1.181061e+1;
t30 = qd1.*t8.*8.50378284;
t31 = qd2.*t8.*8.50378284;
t32 = qd3.*t8.*8.50378284;
t26 = qd1.*t11.*7.99971984;
t27 = qd2.*t11.*7.99971984;
t28 = qd3.*t11.*7.99971984;
t29 = qd4.*t11.*7.99971984;
Iacc = [Q1+qd2.*(t15+t18+t22+t23+t24+t25+t26+t27+t28+t29+t30+t31+t32)+qd1.*(t15+t18+t22+t23+t25+t27+t28+t29+t31+t32)+qd3.*(t15+t16+t17+t18+t20+t21+t22+t23+t26+t27+t28+t29+t30+t31+t32)+qd4.*t10.*(t4.*3.75e+2+t9.*3.75e+2+t11.*2.54e+2).*3.149496e-2,Q2+qd2.*(t15+t18+t22+t23)+qd1.*(t15+t18+t22+t23-t24-t26-t30)+qd3.*(t15+t16+t17+t18+t20+t21+t22+t23)+qd4.*t10.*(t4+t9).*1.181061e+1,Q3+qd4.*t14+t10.*t15-qd1.*(t16+t17+t19+t20+t21+t26+t30)-qd2.*(t16+t17+t19+t20+t21),Q4-qd2.*(t12+t13+t14+t20+t21)-qd1.*(t12+t13+t14+t20+t21+t26)-qd3.*t4.*(qd1+qd2+qd3).*1.181061e+1];
