function out1 = six_J2(q1,q2,q3,q4,q5,q6)
%SIX_J2
%    OUT1 = SIX_J2(Q1,Q2,Q3,Q4,Q5,Q6)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    17-May-2020 16:40:58

t2 = q1+q2;
t3 = cos(t2);
t4 = sin(t2);
t5 = q3+q4+t2;
t6 = cos(t5);
t7 = q5+t5;
t8 = sin(t5);
t11 = t3.*(2.0./5.0);
t12 = t4.*(2.0./5.0);
t9 = sin(t7);
t10 = cos(t7);
t13 = -t12;
t14 = t6.*(2.0./5.0);
t15 = t8.*(2.0./5.0);
t16 = t10./2.0;
t17 = t9./2.0;
t18 = -t15;
t19 = -t17;
t20 = t14+t16;
t21 = t18+t19;
out1 = reshape([t13+t21-sin(q1).*(4.3e+1./1.0e+2),t11+t20+cos(q1).*(4.3e+1./1.0e+2),0.0,0.0,0.0,1.0,t13+t21,t11+t20,0.0,0.0,0.0,1.0,t21,t20,0.0,0.0,0.0,1.0,t21,t20,0.0,0.0,0.0,1.0,t19,t16,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,6]);
