function beta_grf_toe = beta_grf_toe(in1,th)
%BETA_GRF_TOE
%    BETA_GRF_TOE = BETA_GRF_TOE(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    27-May-2020 01:00:18

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
t2 = sin(q1);
t3 = q1+q2;
t7 = th.*4.0e+2;
t14 = atan(2.87940379403794e-1);
t15 = atan(3.472941176470588);
t16 = 1.535969075209524e+3;
t4 = cos(t3);
t5 = sin(t3);
t6 = q3+q4+t3;
t11 = -t7;
t17 = t2.*1.81008e+2;
t18 = -t15;
t8 = cos(t6);
t9 = q5+t6;
t10 = sin(t6);
t28 = t4.*4.38012e-1;
t29 = t5.*4.38012e-1;
t30 = t5.*1.752048e+2;
t12 = sin(t9);
t13 = cos(t9);
t19 = q6+t9+t14;
t24 = q6+t9+t18;
t32 = t8.*4.38012e-1;
t33 = t10.*4.38012e-1;
t34 = t10.*1.752048e+2;
t20 = t12.*1.81008e+2;
t21 = cos(t19);
t22 = t13.*4.5252e-1;
t23 = t12.*4.5252e-1;
t25 = cos(t24);
t26 = t16.*t21.*1.8e-4;
t27 = t16.*t25.*(9.0./1.25e+2);
t31 = t16.*t25.*1.8e-4;
t35 = t22+t26+t32;
t36 = t23+t31+t33;
t37 = t11+t17+t20+t27+t30+t34;
t38 = tanh(t37);
t39 = t38./2.0;
t40 = t39-1.0./2.0;
t41 = t35.*t40;
t43 = t36.*t40;
t42 = -t41;
beta_grf_toe = reshape([t40.*(t2.*4.5252e-1+t29+t36),t40.*(t29+t36),t43,t43,t40.*(t23+t31),t31.*t40,-t40.*(t28+t35+cos(q1).*4.5252e-1),-t40.*(t28+t35),t42,t42,-t40.*(t22+t26),t16.*t21.*t40.*(-1.8e-4)],[6,2]);
