function dbeta_heel_dx6 = dbeta_heel_dx6(in1,th)
%DBETA_HEEL_DX6
%    DBETA_HEEL_DX6 = DBETA_HEEL_DX6(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    02-Jun-2020 13:54:33

dbeta_heel_dx6 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[6,3]);
