function Fn_toe2 = Fn_toe2(in1,th)
%FN_TOE2
%    FN_TOE2 = FN_TOE2(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Jun-2020 12:16:50

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
qd1 = in1(:,7);
qd2 = in1(:,8);
qd3 = in1(:,9);
qd4 = in1(:,10);
qd5 = in1(:,11);
qd6 = in1(:,12);
t2 = q1+q2;
t3 = cos(t2);
t4 = q3+q4+t2;
t5 = cos(t4);
t6 = q5+t4;
t9 = t3.*4.38012e-1;
t7 = cos(t6);
t10 = t5.*4.38012e-1;
t11 = q6+t6+3.902467605501841e-1;
t8 = t7.*4.5252e-1;
t12 = cos(t11);
t13 = t12.*2.010953071953694e-1;
t14 = t8+t10+t13;
Fn_toe2 = qd2.*(t9+t14).*-1.5e+3-qd5.*(t8+t13).*1.5e+3-qd3.*t14.*1.5e+3-qd4.*t14.*1.5e+3-qd6.*t12.*3.016429607930541e+2-qd1.*(t9+t14+cos(q1).*4.5252e-1).*1.5e+3+(th-sin(q1).*4.5252e-1-sin(t2).*4.38012e-1-sin(t4).*4.38012e-1-sin(t6).*4.5252e-1-1.535969075209524e+3.*cos(q6+t6-atan(3.472941176470588)).*1.8e-4).^(1.1e+1./5.0).*1.0e+7;
