function Fs_heel1_d = Fs_heel1_d(in1,th)
%FS_HEEL1_D
%    FS_HEEL1_D = FS_HEEL1_D(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    11-Jun-2020 18:31:07

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = cos(q5);
t7 = sin(q1);
t8 = sin(q2);
t9 = sin(q3);
t10 = sin(q4);
t11 = sin(q5);
t12 = t2.*t3;
t13 = t2.*t8;
t14 = t3.*t7;
t15 = t7.*t8;
t16 = -t15;
t17 = t13+t14;
t18 = t12+t16;
t19 = t4.*t17;
t20 = t9.*t17;
t21 = t4.*t18;
t22 = t9.*t18;
t23 = -t20;
t24 = t19+t22;
t25 = t21+t23;
t28 = -t5.*(t20-t21);
t29 = -t10.*(t20-t21);
t26 = t5.*t24;
t27 = t10.*t24;
t30 = -t27;
t31 = t26+t29;
t32 = t28+t30;
Fs_heel1_d = (tanh(t7.*1.81008e+2+t13.*1.752048e+2+t14.*1.752048e+2+t26.*1.752048e+2-th.*4.0e+2-t11.*(t27+t5.*(t20-t21)).*2.11608e+2+t6.*t31.*2.11608e+2-t10.*(t20-t21).*1.752048e+2)./2.0-1.0./2.0).*(t7.*4.5252e-1+t13.*4.38012e-1+t14.*4.38012e-1+t26.*4.38012e-1-th-t11.*(t27+t5.*(t20-t21)).*5.2902e-1+t6.*t31.*5.2902e-1-t10.*(t20-t21).*4.38012e-1).^2.*-8.0e+4;
