function Fs_heel2_d = Fs_heel2_d(in1,th)
%FS_HEEL2_D
%    FS_HEEL2_D = FS_HEEL2_D(IN1,TH)

%    This function was generated by the Symbolic Math Toolbox version 8.5.
%    09-Jun-2020 12:16:56

q1 = in1(:,1);
q2 = in1(:,2);
q3 = in1(:,3);
q4 = in1(:,4);
q5 = in1(:,5);
q6 = in1(:,6);
qd1 = in1(:,7);
qd2 = in1(:,8);
qd3 = in1(:,9);
qd4 = in1(:,10);
qd5 = in1(:,11);
qd6 = in1(:,12);
t2 = cos(q1);
t3 = cos(q2);
t4 = cos(q3);
t5 = cos(q4);
t6 = sin(q1);
t7 = sin(q2);
t8 = sin(q3);
t9 = sin(q4);
t10 = q1+q2;
t11 = cos(t10);
t12 = t2.*t3;
t13 = t2.*t7;
t14 = t3.*t6;
t15 = q3+q4+t10;
t16 = t6.*t7;
t17 = cos(t15);
t18 = q5+t15;
t19 = -t16;
t21 = t13+t14;
t31 = t11.*4.38012e-1;
t20 = cos(t18);
t22 = t12+t19;
t23 = t4.*t21;
t24 = t8.*t21;
t32 = t17.*4.38012e-1;
t33 = q6+t18+3.902467605501841e-1;
t25 = t4.*t22;
t26 = t8.*t22;
t27 = -t24;
t28 = t20.*4.5252e-1;
t34 = cos(t33);
t29 = t23+t26;
t30 = t25+t27;
t35 = t34.*2.010953071953694e-1;
t36 = t28+t32+t35;
Fs_heel2_d = qd5.*(t28+t35).*-1.05e+3-qd2.*(t31+t36).*1.05e+3+(t6.*(-4.5252e-1)-t13.*4.38012e-1-t14.*4.38012e-1+th-t5.*t29.*4.38012e-1-cos(q5).*(t5.*t29-t9.*(t24-t25)).*5.2902e-1+sin(q5).*(t9.*t29+t5.*(t24-t25)).*5.2902e-1+t9.*(t24-t25).*4.38012e-1).^(1.1e+1./5.0).*7.0e+6-qd3.*t36.*1.05e+3-qd4.*t36.*1.05e+3-qd6.*t34.*2.111500725551379e+2-qd1.*(t2.*4.5252e-1+t31+t36).*1.05e+3;
