function sigma_knee = sigma_knee(q2)
%SIGMA_KNEE
%    SIGMA_KNEE = SIGMA_KNEE(Q2)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    26-May-2020 13:16:09

sigma_knee = tanh(q2.*2.5e+2-pi.*(2.5e+1./3.6e+1)).*(-1.0./2.0)+1.0./2.0;
